// apps/playground-angular/src/fields/select-field.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
  output
} from '@angular/core'
import type { Option } from '@midstem/playground-core'

let nextId = 0

@Component({
  selector: 'app-select-field',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-col gap-1">
      <label
        [class]="
          labelHidden()
            ? 'sr-only'
            : 'font-mono text-xs font-semibold tracking-tight text-ink'
        "
        [attr.for]="id"
      >
        {{ label() }}
      </label>
      <select
        [id]="id"
        class="field-control"
        [value]="value()"
        (change)="onChange($event)"
      >
        @for (option of options(); track option.value) {
          <option [value]="option.value">
            {{ option.label }}
          </option>
        }
      </select>
      @if (hint()) {
        <span class="text-[11px] leading-4 text-muted">{{ hint() }}</span>
      }
    </div>
  `
})
export class SelectFieldComponent {
  readonly id = `select-field-${++nextId}`

  readonly label = input.required<string>()
  readonly hint = input<string>()
  readonly labelHidden = input<boolean>(false)
  readonly value = input.required<string>()
  readonly options = input.required<readonly Option[]>()
  readonly valueChange = output<string>()

  onChange(event: Event): void {
    const target = event.target as HTMLSelectElement
    this.valueChange.emit(target.value)
  }
}

// apps/playground-vue/src/fields/SelectField.vue
<script setup lang="ts">
import { useId } from 'vue'
import type { Option } from '@midstem/playground-core'

defineProps<{
  label: string
  labelHidden?: boolean
  hint?: string
  value: string
  options: readonly Option[]
}>()

const emit = defineEmits<{
  (e: 'update:value', value: string): void
}>()

const id = useId()
</script>

<template>
  <div class="flex flex-col gap-1">
    <label
      :class="
        labelHidden
          ? 'sr-only'
          : 'font-mono text-xs font-semibold tracking-tight text-ink'
      "
      :for="id"
    >
      {{ label }}
    </label>
    <select
      :id="id"
      class="field-control"
      :value="value"
      @change="emit('update:value', ($event.target as HTMLSelectElement).value)"
    >
      <option
        v-for="option of options"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
    <span v-if="hint" class="text-[11px] leading-4 text-muted">{{ hint }}</span>
  </div>
</template>
