// apps/playground-react/src/app/index.tsx
import { useState } from 'react'
import type { ReactElement } from 'react'

import { Board } from '../board'
import { Boundary } from '../boundary'
import { Controls } from '../controls'
import { hourHeightOf } from '../density'
import { Events } from '../events'
import { presetOf } from '../fixtures'
import { Masthead } from '../masthead'
import { DEFAULT_MODE } from '../mode'
import type { Mode } from '../mode'
import { usePlayground } from '../playground'
import { Sidebar } from '../sidebar'
import { Snippet } from '../snippet'
import { useColorScheme } from '../theme'

export const App = (): ReactElement => {
  const playground = usePlayground()
  const scheme = useColorScheme()
  const [mode, setMode] = useState<Mode>(DEFAULT_MODE)
  const { state, range, source, events, problem } = playground

  return (
    <div className="flex h-dvh flex-col overflow-hidden bg-canvas text-ink">
      <Masthead
        mode={mode}
        scheme={scheme}
        onMode={setMode}
        onReset={playground.reset}
      />

      <div className="grid min-h-0 flex-1 grid-cols-1 grid-rows-[minmax(0,16rem)_minmax(0,1fr)] lg:grid-cols-[minmax(300px,23vw)_minmax(0,1fr)] lg:grid-rows-1">
        <Sidebar
          range={
            <Controls
              state={state}
              update={playground.update}
              choosePreset={playground.choosePreset}
            />
          }
          events={
            <Events
              source={source}
              problem={problem}
              hint={presetOf(state.preset).hint}
              count={events.length}
              onChange={playground.changeSource}
            />
          }
        />

        <main className="flex min-h-0 min-w-0 flex-col">
          {mode === 'calendar' && (
            <Boundary key={JSON.stringify(range)}>
              <Board
                range={range}
                events={events}
                locale={state.locale}
                density={state.density}
                style={state.style}
                onNavigate={playground.applyRange}
                onDensity={(density) => playground.update({ density })}
              />
            </Boundary>
          )}

          {mode === 'code' && (
            <Snippet
              range={range}
              events={events}
              locale={state.locale}
              hourHeight={hourHeightOf(state.density)}
              style={state.style}
            />
          )}
        </main>
      </div>
    </div>
  )
}

// apps/playground-svelte/src/App.svelte
<script lang="ts">
  import type { CalendarRange, EventInput } from '@midstem/chronous-svelte'
  import {
    INITIAL_STATE,
    DEFAULT_MODE,
    DEFAULT_PRESET,
    presetOf,
    hourHeightOf
  } from '@midstem/playground-core'
  import type {
    EventData,
    Mode,
    PlaygroundState,
    PresetId
  } from '@midstem/playground-core'
  import {
    parseEvents as parse,
    rangeOf as makeRange,
    sourceOf as makeSource
  } from '@midstem/playground-core'
  import { snippetOf } from './snippet'
  import Board from './components/Board.svelte'
  import Sidebar from './components/Sidebar.svelte'
  import Masthead from './components/Masthead.svelte'
  import Code from './components/Code.svelte'

  let config = $state<PlaygroundState>({ ...INITIAL_STATE })
  let source = $state(makeSource(DEFAULT_PRESET.events))
  let events = $state<readonly EventInput<EventData>[]>(DEFAULT_PRESET.events)
  let problem = $state<string | null>(null)
  let mode = $state<Mode>(DEFAULT_MODE)
  let range = $derived(makeRange(config))
  let hourHeight = $derived(hourHeightOf(config.density))
  let generated = $derived(
    snippetOf(range, events, config.locale, hourHeight, config.style)
  )

  const update = (patch: Partial<PlaygroundState>): void => {
    config = { ...config, ...patch }
  }

  const changeSource = (next: string): void => {
    source = next
    const parsed = parse(next)
    problem = parsed.problem
    if (parsed.problem === null && parsed.events !== null)
      events = parsed.events
  }

  const choosePreset = (id: PresetId): void => {
    const preset = presetOf(id)
    config = {
      ...config,
      preset: id,
      view: preset.view,
      currentDate: preset.date,
      timeZone: preset.timeZone
    }
    source = makeSource(preset.events)
    events = preset.events
    problem = null
  }

  const applyRange = (next: CalendarRange): void => {
    update({
      view: next.view,
      currentDate: next.currentDate,
      timeZone: next.timeZone
    })
  }

  const reset = (): void => {
    config = { ...INITIAL_STATE }
    source = makeSource(DEFAULT_PRESET.events)
    events = DEFAULT_PRESET.events
    problem = null
    mode = DEFAULT_MODE
  }
</script>

<div class="flex h-dvh flex-col overflow-hidden bg-canvas text-ink">
  <Masthead {mode} {reset} onMode={(next) => (mode = next)} />
  <div
    class="grid min-h-0 flex-1 grid-cols-1 grid-rows-[minmax(0,16rem)_minmax(0,1fr)] lg:grid-cols-[minmax(300px,23vw)_minmax(0,1fr)] lg:grid-rows-1"
  >
    <Sidebar
      {config}
      {source}
      {problem}
      {events}
      {update}
      {choosePreset}
      {changeSource}
    />
    <main class="flex min-h-0 min-w-0 flex-col">
      {#if mode === 'calendar'}
        <Board
          {range}
          {events}
          locale={config.locale}
          density={config.density}
          style={config.style}
          onNavigate={applyRange}
          onDensity={(density) => update({ density })}
        />
      {:else}
        <Code
          source={generated}
          {range}
          {events}
          locale={config.locale}
          {hourHeight}
        />
      {/if}
    </main>
  </div>
</div>
