// apps/playground-vue/src/board/Board.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { CalendarRange, EventInput, LocaleId } from '@midstem/chronous-vue'
import { Calendar, useCalendarNavigation, useNow } from '@midstem/chronous-vue'
import {
  GUTTER,
  MONTH_VIEW,
  hourHeightOf,
  isSimple,
  isSlotted,
  titleOf
} from '@midstem/playground-core'
import type { Density, EventData, Style } from '@midstem/playground-core'

import Agenda from '../agenda/Agenda.vue'
import Slotted from '../grid/Slotted.vue'
import Month from '../month/Month.vue'
import PlainAgenda from '../plain/PlainAgenda.vue'
import PlainMonth from '../plain/PlainMonth.vue'
import PlainSlotted from '../plain/PlainSlotted.vue'
import State from '../state/State.vue'
import Toolbar from '../toolbar/Toolbar.vue'

const props = defineProps<{
  range: CalendarRange
  events: readonly EventInput<EventData>[]
  locale: LocaleId
  density: Density
  style: Style
}>()

const emit = defineEmits<{
  (e: 'navigate', range: CalendarRange): void
  (e: 'density', density: Density): void
}>()

const navigation = useCalendarNavigation(() => props.range)
const now = useNow(() => props.range.timeZone)
const today = computed(() => now.value?.date ?? null)
const hourHeight = computed(() => hourHeightOf(props.density))
const plain = computed(() => isSimple(props.style))
</script>

<template>
  <Calendar.Root
    :range="range"
    :events="events"
    :locale="locale"
    :gutter-width="GUTTER"
    class="flex min-h-0 flex-1 flex-col p-4"
  >
    <template #error="error">
      <Toolbar
        :navigation="navigation.value"
        :title="range.currentDate"
        :view="range.view"
        :density="density"
        :slotted="isSlotted(range.view)"
        @navigate="emit('navigate', $event)"
        @density="emit('density', $event)"
      />
      <p
        role="alert"
        class="rounded-lg border border-danger/40 bg-danger-soft px-4 py-3 text-sm text-danger"
      >
        <strong class="font-mono">{{ error.name }}</strong>: {{ error.message }}
      </p>
    </template>

    <template #default="{ calendar }">
      <Toolbar
        :navigation="navigation.value"
        :title="titleOf(calendar, locale)"
        :view="range.view"
        :density="density"
        :slotted="isSlotted(range.view)"
        @navigate="emit('navigate', $event)"
        @density="emit('density', $event)"
      />

      <section
        class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-line bg-surface shadow-sm"
      >
        <div data-scroller class="min-h-0 flex-1 overflow-auto">
          <template v-if="isSlotted(range.view)">
            <PlainSlotted v-if="plain" :hour-height="hourHeight" />
            <Slotted
              v-else
              :locale="locale"
              :hour-height="hourHeight"
              :today="today"
            />
          </template>
          <template v-else-if="range.view === MONTH_VIEW">
            <PlainMonth v-if="plain" />
            <Month v-else :today="today" />
          </template>
          <template v-else>
            <PlainAgenda v-if="plain" />
            <Agenda v-else :locale="locale" :today="today" />
          </template>
        </div>

        <State :calendar="calendar" />
      </section>
    </template>
  </Calendar.Root>
</template>

// apps/playground-svelte/src/components/Board.svelte
<script lang="ts">
  import type {
    CalendarRange,
    EventInput,
    LocaleId
  } from '@midstem/chronous-svelte'
  import { createCalendarComponents, useNow } from '@midstem/chronous-svelte'
  import {
    BACK_LABEL,
    DENSITIES,
    DENSITY_LABEL,
    GUTTER,
    NEXT_LABEL,
    VIEWS,
    hourHeightOf,
    isSimple,
    isSlotted,
    titleOf
  } from '@midstem/playground-core'
  import type { Density, EventData, Style } from '@midstem/playground-core'
  import State from './State.svelte'
  import Slotted from './Slotted.svelte'
  import Month from './Month.svelte'
  import Agenda from './Agenda.svelte'

  const C = createCalendarComponents<EventData>()
  let {
    range,
    events,
    locale,
    density,
    style,
    onNavigate,
    onDensity
  }: {
    range: CalendarRange
    events: readonly EventInput<EventData>[]
    locale: LocaleId
    density: Density
    style: Style
    onNavigate: (range: CalendarRange) => void
    onDensity: (density: Density) => void
  } = $props()
  let now = $derived(useNow(range.timeZone))
  let today = $derived($now?.date ?? null)
  let hourHeight = $derived(hourHeightOf(density))
  let plain = $derived(isSimple(style))
</script>

<C.Root
  {range}
  {events}
  {locale}
  gutterWidth={GUTTER}
  class="flex min-h-0 flex-1 flex-col p-4"
>
  {#snippet renderError(error)}
    <div class="flex min-h-0 flex-1 flex-col gap-3 p-4">
      <p
        role="alert"
        class="rounded-lg border border-danger/40 bg-danger-soft px-4 py-3 text-sm text-danger"
      >
        <strong class="font-mono">{error.name}</strong>: {error.message}
      </p>
    </div>
  {/snippet}
  {#snippet children({ calendar })}
    {@render Toolbar(titleOf(calendar, locale))}
    <section
      class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-line bg-surface shadow-sm"
    >
      <div data-scroller class="min-h-0 flex-1 overflow-auto">
        {#if isSlotted(range.view)}
          <Slotted {locale} {hourHeight} {today} {plain} />
        {:else if range.view === 'month'}
          <Month {today} {plain} />
        {:else}
          <Agenda {locale} {today} {plain} />
        {/if}
      </div>
      <State {calendar} />
    </section>
  {/snippet}
</C.Root>

{#snippet Toolbar(calendarTitle: string)}
  <C.Toolbar {onNavigate} views={VIEWS}>
    {#snippet children({ navigation: nav, goTo, range: shown })}
      <header class="flex flex-wrap items-center gap-3 pb-3">
        <div class="flex items-center gap-1">
          <button
            type="button"
            class="ghost-button"
            aria-label={BACK_LABEL}
            disabled={!nav.prev}
            onclick={() => nav.prev && goTo(nav.prev)}>‹</button
          ><button
            type="button"
            class="ghost-button"
            disabled={!nav.today}
            onclick={() => nav.today && goTo(nav.today())}>Today</button
          ><button
            type="button"
            class="ghost-button"
            aria-label={NEXT_LABEL}
            disabled={!nav.next}
            onclick={() => nav.next && goTo(nav.next)}>›</button
          >
        </div>
        <h2 class="mr-auto truncate text-lg font-semibold">{calendarTitle}</h2>
        {#if isSlotted(range.view)}
          <div class="flex flex-col gap-1">
            <span class="px-1 text-[10px] font-medium text-muted"
              >Row height</span
            >
            <div
              class="flex items-center gap-0.5 rounded-lg border border-line bg-surface p-0.5"
              role="group"
              aria-label={DENSITY_LABEL}
            >
              {#each DENSITIES as option (option.value)}
                <button
                  type="button"
                  title={`${option.value} row height · ${option.hourHeight}px per hour`}
                  class={`rounded-md px-2 py-1 text-xs font-medium ${
                    option.value === density
                      ? 'bg-accent-soft text-accent'
                      : 'text-muted hover:text-ink'
                  }`}
                  aria-pressed={option.value === density}
                  onclick={() => onDensity(option.value)}>{option.label}</button
                >
              {/each}
            </div>
          </div>
        {/if}
        <div class="flex flex-col gap-1">
          <span class="px-1 text-[10px] font-medium text-muted">View</span>
          <div
            class="flex items-center gap-0.5 rounded-lg border border-line bg-surface p-0.5"
            role="group"
            aria-label="View"
          >
            {#each VIEWS as view (view)}
              <button
                type="button"
                class={`rounded-md px-2.5 py-1 text-xs font-medium capitalize ${
                  view === shown.view
                    ? 'bg-accent-soft text-accent'
                    : 'text-muted hover:text-ink'
                }`}
                aria-pressed={view === shown.view}
                onclick={() => goTo(nav.withView(view))}>{view}</button
              >
            {/each}
          </div>
        </div>
      </header>
    {/snippet}
  </C.Toolbar>
{/snippet}
