// packages/svelte/src/components/slotted/NowMarker.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { CalendarNow } from './use-now'
  import { useCalendarContext, useDayColumnContext } from '../context'
  import { minutePercentOf, styleText } from '../helpers'
  import { useNow } from './use-now'
  type NowMarkerScope = { minuteOfDay: number }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[NowMarkerScope]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const calendarContext = useCalendarContext()
  const dayContext = useDayColumnContext()
  let now = $state<CalendarNow | null>(null)
  $effect(() =>
    useNow(calendarContext.range.timeZone).subscribe((value) => {
      now = value
    })
  )
</script>

{#if now && now.date === dayContext.day.date}<svelte:element
    this={as}
    {...rest}
    style={styleText(
      {
        position: 'absolute',
        left: 0,
        right: 0,
        top: minutePercentOf(now.minuteOfDay),
        zIndex: 10
      },
      style
    )}
    >{#if children}{@render children({
        minuteOfDay: now.minuteOfDay
      })}{/if}</svelte:element
  >{/if}

// packages/angular/src/directives/slotted/now-marker.ts
import type { CalendarDay } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  computed,
  effect,
  inject,
  input
} from '@angular/core'

import { injectNow } from '../../now'
import type { CalendarNow } from '../../now'
import { injectCalendarContext } from '../context'
import { contextOf, minutePercentOf } from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'

const Z_INDEX = '10'

export type NowMarkerScope = {
  minuteOfDay: number
}

export type NowMarkerContext = ScopedContext<number, NowMarkerScope>

@Directive({ selector: '[chronousNowMarker]', exportAs: 'chronousNowMarker' })
export class NowMarkerDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: NowMarkerDirective<TData>,
    _context: unknown
  ): _context is NowMarkerContext {
    return true
  }

  readonly day = input.required<CalendarDay<TData>>({
    alias: 'chronousNowMarker'
  })

  readonly #calendar = injectCalendarContext<TData>()

  readonly #now = injectNow(() => this.#calendar.range().timeZone)

  readonly onDay = computed((): CalendarNow[] => {
    const now = this.#now()

    return now && now.date === this.day().date ? [now] : []
  })

  readonly #container = inject(ViewContainerRef)

  readonly #template = inject<TemplateRef<NowMarkerContext>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #render(): void {
    syncViews(this.#container, this.#template, this.onDay(), {
      contextOf: (now) =>
        contextOf(now.minuteOfDay, { minuteOfDay: now.minuteOfDay }),
      styleOf: (now) => ({
        position: 'absolute',
        left: '0',
        right: '0',
        top: minutePercentOf(now.minuteOfDay),
        'z-index': Z_INDEX
      })
    })
  }
}
