// packages/react/src/components/slotted/time-labels.tsx
import type { CalendarSlot } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import {
  CLOCK,
  labelOf,
  minutePercentOf,
  renderChildren,
  styleOf,
  tagOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type TimeLabelScope = {
  slot: CalendarSlot
  minuteOfDay: number
  timeLabel: string
}

export type TimeLabelsProps<TTag extends ElementType = 'div'> =
  PolymorphicProps<TTag, OwnProps<TimeLabelScope>>

export const TimeLabels = <TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: TimeLabelsProps<TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext()
  const Tag = tagOf(as, 'div')
  const day = calendar.days[0]

  return (
    <>
      {day.slots.map((slot) => {
        const timeLabel = labelOf(slot.start, locale, CLOCK)

        return (
          <Tag
            key={slot.minuteOfDay}
            {...rest}
            style={styleOf(
              {
                position: 'absolute',
                top: minutePercentOf(slot.minuteOfDay),
                transform: 'translateY(-50%)'
              },
              style
            )}
          >
            {renderChildren(
              children,
              { slot, minuteOfDay: slot.minuteOfDay, timeLabel },
              timeLabel
            )}
          </Tag>
        )
      })}
    </>
  )
}

// packages/angular/src/directives/slotted/time-labels.ts
import type { CalendarSlot } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject
} from '@angular/core'

import { injectCalendarContext } from '../context'
import { CLOCK, contextOf, labelOf, minutePercentOf } from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'

export type TimeLabelScope = {
  slot: CalendarSlot
  minuteOfDay: number
  timeLabel: string
}

export type TimeLabelContext = ScopedContext<CalendarSlot, TimeLabelScope>

@Directive({ selector: '[chronousTimeLabels]', exportAs: 'chronousTimeLabels' })
export class TimeLabelsDirective {
  static ngTemplateContextGuard(
    _directive: TimeLabelsDirective,
    _context: unknown
  ): _context is TimeLabelContext {
    return true
  }

  readonly #calendar = injectCalendarContext()

  readonly #container = inject(ViewContainerRef)

  readonly #template = inject<TemplateRef<TimeLabelContext>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #render(): void {
    const locale = this.#calendar.locale()
    const day = this.#calendar.calendar().days[0]

    syncViews(this.#container, this.#template, day.slots, {
      contextOf: (slot) =>
        contextOf(slot, {
          slot,
          minuteOfDay: slot.minuteOfDay,
          timeLabel: labelOf(slot.start, locale, CLOCK)
        }),
      styleOf: (slot) => ({
        position: 'absolute',
        top: minutePercentOf(slot.minuteOfDay),
        transform: 'translateY(-50%)'
      })
    })
  }
}
