// packages/react/src/components/shared/day-headings.tsx
import type { CalendarDay, IsoDate } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import { DAY_NUMBER, WEEKDAY, labelOf, renderChildren, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type DayHeadingScope<TData> = {
  day: CalendarDay<TData>
  date: IsoDate
  weekdayLabel: string
  dayLabel: string
  inCurrentPeriod: boolean
}

export type DayHeadingsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<DayHeadingScope<TData>>>

export const DayHeadings = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: DayHeadingsProps<TData, TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {calendar.days.map((day) => {
        const weekdayLabel = labelOf(day.date, locale, WEEKDAY)
        const dayLabel = labelOf(day.date, locale, DAY_NUMBER)

        return (
          <Tag
            key={day.date}
            data-date={day.date}
            data-in-current-period={day.inCurrentPeriod}
            {...rest}
            style={style}
          >
            {renderChildren(
              children,
              {
                day,
                date: day.date,
                weekdayLabel,
                dayLabel,
                inCurrentPeriod: day.inCurrentPeriod
              },
              `${weekdayLabel} ${dayLabel}`
            )}
          </Tag>
        )
      })}
    </>
  )
}

// packages/svelte/src/components/shared/DayHeadings.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarDay, IsoDate } from '../../engine.js'
  import { useCalendarContext } from '../context'
  import { DAY_NUMBER, WEEKDAY, labelOf, styleText } from '../helpers'
  type DayHeadingScope<T> = {
    day: CalendarDay<T>
    date: IsoDate
    weekdayLabel: string
    dayLabel: string
    inCurrentPeriod: boolean
  }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[DayHeadingScope<TData>]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext<TData>()
</script>

{#each context.calendar.days as day (day.date)}
  {@const weekdayLabel = labelOf(day.date, context.locale, WEEKDAY)}
  {@const dayLabel = labelOf(day.date, context.locale, DAY_NUMBER)}
  <svelte:element
    this={as}
    data-date={day.date}
    data-in-current-period={day.inCurrentPeriod}
    {...rest}
    style={styleText({}, style)}
  >
    {#if children}
      {@render children({
        day,
        date: day.date,
        weekdayLabel,
        dayLabel,
        inCurrentPeriod: day.inCurrentPeriod
      })}
    {:else}
      {weekdayLabel} {dayLabel}
    {/if}
  </svelte:element>
{/each}
