// packages/react/src/components/shared/header.tsx
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import type { CalendarContextValue } from '../context'
import { renderChildren, styleOf, tagOf, templateOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type HeaderOwnProps<TData> = OwnProps<CalendarContextValue<TData>> & {
  gutterCell?: ReactNode
}

export type HeaderProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, HeaderOwnProps<TData>>

export const Header = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  gutterCell = null,
  ...rest
}: HeaderProps<TData, TTag>): ReactNode => {
  const scope = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <Tag
      {...rest}
      style={styleOf(
        {
          display: 'grid',
          gridTemplateColumns: templateOf(
            scope.gutterWidth,
            scope.calendar.days.length
          )
        },
        style
      )}
    >
      <div>{gutterCell}</div>
      {renderChildren(children, scope, null)}
    </Tag>
  )
}

// packages/svelte/src/components/shared/Header.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { useCalendarContext } from '../context'
  import type { CalendarContextValue } from '../context'
  import { styleText, templateOf } from '../helpers'
  let {
    as = 'div',
    children,
    style,
    gutterCell,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[CalendarContextValue]>
    style?: string | Record<string, string | number>
    gutterCell?: Snippet
    [key: string]: unknown
  } = $props()
  const scope = useCalendarContext()
  let css = $derived(
    styleText(
      {
        display: 'grid',
        gridTemplateColumns: templateOf(
          scope.gutterWidth,
          scope.calendar.days.length
        )
      },
      style
    )
  )
</script>

<svelte:element this={as} {...rest} style={css}
  ><div>
    {#if gutterCell}{@render gutterCell()}{/if}
  </div>
  {#if children}{@render children(scope)}{/if}</svelte:element
>
