// packages/react/src/navigation/index.ts
import type { CalendarRange } from '@midstem/chronous'
import { useMemo } from 'react'

import { useStableRange } from '#src/range'
import { useTemporalStatus } from '#src/temporal'

import { navigationOf } from './helpers'
import type { CalendarNavigation } from './types'

export const useCalendarNavigation = (
  range: CalendarRange
): CalendarNavigation => {
  const held = useStableRange(range)
  const status = useTemporalStatus()

  return useMemo(() => navigationOf(held, status), [held, status])
}

export type * from './types'

// packages/angular/src/navigation/index.ts
import type { CalendarRange } from '@midstem/chronous'
import { computed } from '@angular/core'
import type { Signal } from '@angular/core'

import { stableRange } from '../range'
import { injectTemporalStatus } from '../temporal'

import { navigationOf } from './helpers'
import type { CalendarNavigation } from './types'

export const injectCalendarNavigation = (
  range: () => CalendarRange
): Signal<CalendarNavigation> => {
  const held = stableRange(range)
  const status = injectTemporalStatus()

  return computed(() => navigationOf(held(), status()))
}

export type * from './types'
