// apps/playground-angular/src/plain/plain-month.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { CALENDAR_DIRECTIVES } from '@midstem/chronous-angular'

const LANE_HEIGHT = 20

@Component({
  selector: 'app-plain-month',
  standalone: true,
  imports: [CALENDAR_DIRECTIVES],
  host: {
    class: 'block'
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div chronousMonthGrid>
      <div
        *chronousMonthRows="let row; laneHeight: laneHeight"
        class="border-b border-line last:border-b-0"
      >
        <div
          *chronousMonthDays="
            row;
            let day;
            let dayLabel = dayLabel;
            let lanes = lanes
          "
          class="min-h-28 border-l border-hair p-1 first:border-l-0 data-[in-current-period=false]:bg-sunken data-[in-current-period=false]:text-faint"
        >
          <div class="h-7 text-center text-xs font-medium">
            {{ dayLabel }}
          </div>
          <div [style.height.px]="lanes * laneHeight"></div>
          <div
            *chronousMonthTimedEvents="day; let event"
            class="truncate rounded bg-event-timed px-1 text-[11px] leading-5 text-event-timed-ink"
          >
            {{ event.data?.title ?? event.id }}
          </div>
        </div>

        <div
          *chronousMonthAllDayEvents="row; let event"
          class="truncate rounded bg-event-all-day px-1.5 text-[11px] leading-5 text-event-all-day-ink"
        >
          {{ event.data?.title ?? event.id }}
        </div>
      </div>
    </div>
  `
})
export class PlainMonthComponent {
  readonly laneHeight = LANE_HEIGHT
}

// apps/playground-vue/src/plain/PlainMonth.vue
<script setup lang="ts">
import { Calendar } from '@midstem/chronous-vue'

const LANE_HEIGHT = 20
</script>

<template>
  <Calendar.MonthGrid>
    <Calendar.MonthRows
      class="border-b border-line last:border-b-0"
      :lane-height="LANE_HEIGHT"
    >
      <Calendar.MonthDays
        class="min-h-28 border-l border-hair p-1 first:border-l-0 data-[in-current-period=false]:bg-sunken data-[in-current-period=false]:text-faint"
        v-slot="{ dayLabel, lanes }"
      >
        <div class="h-7 text-center text-xs font-medium">{{ dayLabel }}</div>
        <div :style="{ height: `${lanes * LANE_HEIGHT}px` }" />
        <Calendar.MonthTimedEvents
          class="truncate rounded bg-event-timed px-1 text-[11px] leading-5 text-event-timed-ink"
          v-slot="{ event }"
        >
          {{ event.data?.title }}
        </Calendar.MonthTimedEvents>
      </Calendar.MonthDays>

      <Calendar.MonthAllDayEvents
        class="truncate rounded bg-event-all-day px-1.5 text-[11px] leading-5 text-event-all-day-ink"
        v-slot="{ event }"
      >
        {{ event.data?.title }}
      </Calendar.MonthAllDayEvents>
    </Calendar.MonthRows>
  </Calendar.MonthGrid>
</template>
