// packages/react/src/components/slotted/now-marker.tsx
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext, useDayColumnContext } from '../context'
import { minutePercentOf, renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'
import { useNow } from './use-now'

const Z_INDEX = 10

export type NowMarkerScope = {
  minuteOfDay: number
}

export type NowMarkerProps<TTag extends ElementType = 'div'> = PolymorphicProps<
  TTag,
  OwnProps<NowMarkerScope>
>

export const NowMarker = <TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: NowMarkerProps<TTag>): ReactNode => {
  const { range } = useCalendarContext()
  const { day } = useDayColumnContext()
  const now = useNow(range.timeZone)
  const Tag = tagOf(as, 'div')

  if (!now || now.date !== day.date) return null

  return (
    <Tag
      {...rest}
      style={styleOf(
        {
          position: 'absolute',
          left: 0,
          right: 0,
          top: minutePercentOf(now.minuteOfDay),
          zIndex: Z_INDEX
        },
        style
      )}
    >
      {renderSlot(children, { minuteOfDay: now.minuteOfDay }, null)}
    </Tag>
  )
}

// packages/svelte/src/components/slotted/NowMarker.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { CalendarNow } from './use-now'
  import { useCalendarContext, useDayColumnContext } from '../context'
  import { minutePercentOf, styleText } from '../helpers'
  import { useNow } from './use-now'
  type NowMarkerScope = { minuteOfDay: number }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[NowMarkerScope]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const calendarContext = useCalendarContext()
  const dayContext = useDayColumnContext()
  let now = $state<CalendarNow | null>(null)
  $effect(() =>
    useNow(calendarContext.range.timeZone).subscribe((value) => {
      now = value
    })
  )
</script>

{#if now && now.date === dayContext.day.date}<svelte:element
    this={as}
    {...rest}
    style={styleText(
      {
        position: 'absolute',
        left: 0,
        right: 0,
        top: minutePercentOf(now.minuteOfDay),
        zIndex: 10
      },
      style
    )}
    >{#if children}{@render children({
        minuteOfDay: now.minuteOfDay
      })}{/if}</svelte:element
  >{/if}
