// packages/react/src/components/slotted/time-labels.tsx
import type { CalendarSlot } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import {
  CLOCK,
  labelOf,
  minutePercentOf,
  renderChildren,
  styleOf,
  tagOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type TimeLabelScope = {
  slot: CalendarSlot
  minuteOfDay: number
  timeLabel: string
}

export type TimeLabelsProps<TTag extends ElementType = 'div'> =
  PolymorphicProps<TTag, OwnProps<TimeLabelScope>>

export const TimeLabels = <TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: TimeLabelsProps<TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext()
  const Tag = tagOf(as, 'div')
  const day = calendar.days[0]

  return (
    <>
      {day.slots.map((slot) => {
        const timeLabel = labelOf(slot.start, locale, CLOCK)

        return (
          <Tag
            key={slot.minuteOfDay}
            {...rest}
            style={styleOf(
              {
                position: 'absolute',
                top: minutePercentOf(slot.minuteOfDay),
                transform: 'translateY(-50%)'
              },
              style
            )}
          >
            {renderChildren(
              children,
              { slot, minuteOfDay: slot.minuteOfDay, timeLabel },
              timeLabel
            )}
          </Tag>
        )
      })}
    </>
  )
}

// packages/svelte/src/components/slotted/TimeLabels.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { CalendarSlot } from '../../engine.js'
  import { useCalendarContext } from '../context'
  import { CLOCK, labelOf, minutePercentOf, styleText } from '../helpers'
  type TimeLabelScope = {
    slot: CalendarSlot
    minuteOfDay: number
    timeLabel: string
  }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[TimeLabelScope]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext()
  let day = $derived(context.calendar.days[0])
</script>

{#each day.slots as slot (slot.minuteOfDay)}
  {@const timeLabel = labelOf(slot.start, context.locale, CLOCK)}
  <svelte:element
    this={as}
    {...rest}
    style={styleText(
      {
        position: 'absolute',
        top: minutePercentOf(slot.minuteOfDay),
        transform: 'translateY(-50%)'
      },
      style
    )}
    >{#if children}{@render children({
        slot,
        minuteOfDay: slot.minuteOfDay,
        timeLabel
      })}{:else}{timeLabel}{/if}</svelte:element
  >
{/each}
