// packages/react/src/components/slotted/timed-events.tsx
import type { CalendarBox, TimedEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useDayColumnContext } from '../context'
import { percentOf, renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const MIN_HEIGHT = 22

const GAP = 3

export type TimedEventScope<TData> = {
  event: TimedEntry<TData>
  box: CalendarBox<TData>
}

export type TimedEventsOwnProps<TData> = OwnProps<TimedEventScope<TData>> & {
  minHeight?: number
  gap?: number
}

export type TimedEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, TimedEventsOwnProps<TData>>

export const TimedEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  minHeight = MIN_HEIGHT,
  gap = GAP,
  ...rest
}: TimedEventsProps<TData, TTag>): ReactNode => {
  const { day } = useDayColumnContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {day.boxes.map((box) => (
        <Tag
          key={`${box.event.id}-${box.startMinute}`}
          data-event-id={box.event.id}
          data-continues-before={box.continuesBefore}
          data-continues-after={box.continuesAfter}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              overflow: 'hidden',
              top: percentOf(box.top),
              height: percentOf(box.height),
              left: percentOf(box.left),
              width: `calc(${percentOf(box.width)} - ${gap}px)`,
              minHeight
            },
            style
          )}
        >
          {renderSlot(children, { event: box.event, box }, box.event.id)}
        </Tag>
      ))}
    </>
  )
}

// packages/svelte/src/components/slotted/TimedEvents.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarBox, TimedEntry } from '../../engine.js'
  import { useDayColumnContext } from '../context'
  import { percentOf, styleText } from '../helpers'
  type TimedEventScope<T> = { event: TimedEntry<T>; box: CalendarBox<T> }
  let {
    as = 'div',
    children,
    style,
    minHeight = 22,
    gap = 3,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[TimedEventScope<TData>]>
    style?: string | Record<string, string | number>
    minHeight?: number
    gap?: number
    [key: string]: unknown
  } = $props()
  const context = useDayColumnContext<TData>()
</script>

{#each context.day.boxes as box (`${box.event.id}-${box.startMinute}`)}
  <svelte:element
    this={as}
    data-event-id={box.event.id}
    data-continues-before={box.continuesBefore}
    data-continues-after={box.continuesAfter}
    {...rest}
    style={styleText(
      {
        position: 'absolute',
        overflow: 'hidden',
        top: percentOf(box.top),
        height: percentOf(box.height),
        left: percentOf(box.left),
        width: `calc(${percentOf(box.width)} - ${gap}px)`,
        minHeight
      },
      style
    )}
  >
    {#if children}
      {@render children({ event: box.event, box })}
    {:else}
      {box.event.id}
    {/if}
  </svelte:element>
{/each}
