// packages/react/src/components/slotted/time-grid.tsx
import type { ElementType, ReactNode } from 'react'
import { useEffect, useRef } from 'react'

import { TimeGridProvider, useCalendarContext } from '../context'
import type { TimeGridContextValue } from '../context'
import {
  HOURS_IN_DAY,
  renderChildren,
  styleOf,
  tagOf,
  templateOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'
import { scrollerOf } from './helpers'

const HOUR_HEIGHT = 60

const SCROLL_TO_HOUR = 7

export type TimeGridOwnProps = OwnProps<TimeGridContextValue> & {
  hourHeight?: number
  scrollToHour?: number | null
}

export type TimeGridProps<TTag extends ElementType = 'div'> = PolymorphicProps<
  TTag,
  TimeGridOwnProps
>

export const TimeGrid = <TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  hourHeight = HOUR_HEIGHT,
  scrollToHour = SCROLL_TO_HOUR,
  ...rest
}: TimeGridProps<TTag>): ReactNode => {
  const { calendar, gutterWidth } = useCalendarContext()
  const held = useRef<HTMLElement>(null)
  const Tag = tagOf(as, 'div')

  useEffect(() => {
    if (scrollToHour === null) return

    const scroller = scrollerOf(held.current)

    if (scroller) scroller.scrollTop = hourHeight * scrollToHour
  }, [hourHeight, scrollToHour])

  const scope: TimeGridContextValue = {
    hourHeight,
    dayHeight: hourHeight * HOURS_IN_DAY
  }

  return (
    <TimeGridProvider value={scope}>
      <Tag {...rest} ref={held} style={styleOf({ overflowY: 'auto' }, style)}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: templateOf(gutterWidth, calendar.days.length)
          }}
        >
          {renderChildren(children, scope, null)}
        </div>
      </Tag>
    </TimeGridProvider>
  )
}

// packages/svelte/src/components/slotted/TimeGrid.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { onMount } from 'svelte'
  import { provideTimeGrid, useCalendarContext } from '../context'
  import type { TimeGridContextValue } from '../context'
  import { styleText, templateOf } from '../helpers'
  import { scrollerOf } from './helpers'
  let {
    as = 'div',
    children,
    style,
    hourHeight = 60,
    scrollToHour = 7,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[TimeGridContextValue]>
    style?: string | Record<string, string | number>
    hourHeight?: number
    scrollToHour?: number | null
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext()
  const scope = {
    get hourHeight() {
      return hourHeight
    },
    get dayHeight() {
      return hourHeight * 24
    }
  }
  provideTimeGrid(scope)
  let element: HTMLElement
  let mounted = $state(false)
  onMount(() => {
    mounted = true
  })
  $effect(() => {
    if (!mounted || scrollToHour === null || !element) return
    const scroller = scrollerOf(element)
    if (scroller) scroller.scrollTop = hourHeight * scrollToHour
  })
</script>

<svelte:element
  this={as}
  bind:this={element}
  {...rest}
  style={styleText({ overflowY: 'auto' }, style)}
>
  <div
    style={`display:grid;grid-template-columns:${templateOf(context.gutterWidth, context.calendar.days.length)}`}
  >
    {#if children}{@render children(scope)}{/if}
  </div>
</svelte:element>
