// apps/demo/src/board/index.tsx
import type {
  EventInput,
  IsoDate,
  LocaleId,
  CalendarRange
} from '@midstem/chronous-react'
import { useCalendarNavigation, useNow } from '@midstem/chronous-react'
import type { ReactElement } from 'react'

import { Agenda } from '../agenda'
import { Calendar } from '../calendar'
import type { Density } from '../density'
import { hourHeightOf } from '../density'
import { GUTTER, Slotted } from '../grid'
import { Month } from '../month'
import { PlainAgenda, PlainMonth, PlainSlotted } from '../plain'
import { State } from '../state'
import { isSimple } from '../style'
import type { Style } from '../style'
import { Toolbar } from '../toolbar'
import type { EventData } from '../types'

import { MONTH_VIEW } from './constants'
import { isSlotted, titleOf } from './helpers'

type BoardProps = {
  range: CalendarRange
  events: readonly EventInput<EventData>[]
  locale: LocaleId
  density: Density
  style: Style
  onNavigate: (range: CalendarRange) => void
  onDensity: (density: Density) => void
}

type ViewProps = {
  range: CalendarRange
  locale: LocaleId
  today: IsoDate | null
  hourHeight: number
  style: Style
}

const View = ({
  range,
  locale,
  today,
  hourHeight,
  style
}: ViewProps): ReactElement => {
  const plain = isSimple(style)

  if (isSlotted(range.view))
    return plain ? (
      <PlainSlotted hourHeight={hourHeight} />
    ) : (
      <Slotted locale={locale} hourHeight={hourHeight} today={today} />
    )

  if (range.view === MONTH_VIEW)
    return plain ? <PlainMonth /> : <Month today={today} />

  return plain ? <PlainAgenda /> : <Agenda locale={locale} today={today} />
}

export const Board = ({
  range,
  events,
  locale,
  density,
  style,
  onNavigate,
  onDensity
}: BoardProps): ReactElement => {
  const navigation = useCalendarNavigation(range)
  const now = useNow(range.timeZone)
  const today = now?.date ?? null

  const bar = (title: string): ReactElement => (
    <Toolbar
      navigation={navigation}
      title={title}
      view={range.view}
      density={density}
      slotted={isSlotted(range.view)}
      onChange={onNavigate}
      onDensity={onDensity}
    />
  )

  return (
    <Calendar.Root
      range={range}
      events={events}
      locale={locale}
      gutterWidth={GUTTER}
      className="flex min-h-0 flex-1 flex-col p-4"
      renderError={(error) => (
        <>
          {bar(range.currentDate)}
          <p
            role="alert"
            className="rounded-lg border border-danger/40 bg-danger-soft px-4 py-3 text-sm text-danger"
          >
            <strong className="font-mono">{error.name}</strong>: {error.message}
          </p>
        </>
      )}
    >
      {({ calendar }) => (
        <>
          {bar(titleOf(calendar, locale))}

          <section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-line bg-surface shadow-sm">
            <div data-scroller className="min-h-0 flex-1 overflow-auto">
              <View
                range={range}
                locale={locale}
                today={today}
                hourHeight={hourHeightOf(density)}
                style={style}
              />
            </div>

            <State calendar={calendar} />
          </section>
        </>
      )}
    </Calendar.Root>
  )
}

export { MONTH_VIEW, SLOTTED_VIEWS } from './constants'

// apps/playground-vue/src/board/Board.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { CalendarRange, EventInput, LocaleId } from '@midstem/chronous-vue'
import { Calendar, useCalendarNavigation, useNow } from '@midstem/chronous-vue'
import {
  GUTTER,
  MONTH_VIEW,
  hourHeightOf,
  isSimple,
  isSlotted,
  titleOf
} from '@midstem/playground-core'
import type { Density, EventData, Style } from '@midstem/playground-core'

import Agenda from '../agenda/Agenda.vue'
import Slotted from '../grid/Slotted.vue'
import Month from '../month/Month.vue'
import PlainAgenda from '../plain/PlainAgenda.vue'
import PlainMonth from '../plain/PlainMonth.vue'
import PlainSlotted from '../plain/PlainSlotted.vue'
import State from '../state/State.vue'
import Toolbar from '../toolbar/Toolbar.vue'

const props = defineProps<{
  range: CalendarRange
  events: readonly EventInput<EventData>[]
  locale: LocaleId
  density: Density
  style: Style
}>()

const emit = defineEmits<{
  (e: 'navigate', range: CalendarRange): void
  (e: 'density', density: Density): void
}>()

const navigation = useCalendarNavigation(() => props.range)
const now = useNow(() => props.range.timeZone)
const today = computed(() => now.value?.date ?? null)
const hourHeight = computed(() => hourHeightOf(props.density))
const plain = computed(() => isSimple(props.style))
</script>

<template>
  <Calendar.Root
    :range="range"
    :events="events"
    :locale="locale"
    :gutter-width="GUTTER"
    class="flex min-h-0 flex-1 flex-col p-4"
  >
    <template #error="error">
      <Toolbar
        :navigation="navigation.value"
        :title="range.currentDate"
        :view="range.view"
        :density="density"
        :slotted="isSlotted(range.view)"
        @navigate="emit('navigate', $event)"
        @density="emit('density', $event)"
      />
      <p
        role="alert"
        class="rounded-lg border border-danger/40 bg-danger-soft px-4 py-3 text-sm text-danger"
      >
        <strong class="font-mono">{{ error.name }}</strong>: {{ error.message }}
      </p>
    </template>

    <template #default="{ calendar }">
      <Toolbar
        :navigation="navigation.value"
        :title="titleOf(calendar, locale)"
        :view="range.view"
        :density="density"
        :slotted="isSlotted(range.view)"
        @navigate="emit('navigate', $event)"
        @density="emit('density', $event)"
      />

      <section
        class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-line bg-surface shadow-sm"
      >
        <div data-scroller class="min-h-0 flex-1 overflow-auto">
          <template v-if="isSlotted(range.view)">
            <PlainSlotted v-if="plain" :hour-height="hourHeight" />
            <Slotted
              v-else
              :locale="locale"
              :hour-height="hourHeight"
              :today="today"
            />
          </template>
          <template v-else-if="range.view === MONTH_VIEW">
            <PlainMonth v-if="plain" />
            <Month v-else :today="today" />
          </template>
          <template v-else>
            <PlainAgenda v-if="plain" />
            <Agenda v-else :locale="locale" :today="today" />
          </template>
        </div>

        <State :calendar="calendar" />
      </section>
    </template>
  </Calendar.Root>
</template>
