// packages/angular/src/range/index.ts
import type { CalendarRange } from '@midstem/chronous'
import { computed } from '@angular/core'
import type { Signal } from '@angular/core'

import { sameRange } from './helpers'

export const stableRange = (
  range: () => CalendarRange
): Signal<CalendarRange> => computed(range, { equal: sameRange })

// packages/react/src/range/index.ts
import type { CalendarRange } from '@midstem/chronous'
import { useRef } from 'react'

import { sameRange } from './helpers'

export const useStableRange = (range: CalendarRange): CalendarRange => {
  const held = useRef(range)

  if (!sameRange(held.current, range)) held.current = range

  return held.current
}
