// packages/angular/src/calendar/index.ts
import type { EventInput, CalendarRange } from '@midstem/chronous'
import { computed } from '@angular/core'
import type { Signal } from '@angular/core'

import { stableRange } from '../range'

import { resultOf } from './helpers'
import type { CalendarResult } from './types'

export const injectCalendar = <TData>(
  range: () => CalendarRange,
  events: () => readonly EventInput<TData>[]
): Signal<CalendarResult<TData>> => {
  const held = stableRange(range)

  return computed(() => resultOf(held(), events()))
}

export type * from './types'

// packages/react/src/calendar/index.ts
import type { EventInput, CalendarRange } from '@midstem/chronous'
import { useMemo } from 'react'

import { useStableRange } from '#src/range'

import { resultOf } from './helpers'
import type { CalendarResult } from './types'

export const useCalendar = <TData>(
  range: CalendarRange,
  events: readonly EventInput<TData>[]
): CalendarResult<TData> => {
  const held = useStableRange(range)

  return useMemo(() => resultOf(held, events), [held, events])
}

export type * from './types'
