// apps/demo/src/app/index.tsx
import { useState } from 'react'
import type { ReactElement } from 'react'

import { Board } from '../board'
import { Boundary } from '../boundary'
import { Controls } from '../controls'
import { hourHeightOf } from '../density'
import { Events } from '../events'
import { presetOf } from '../fixtures'
import { Masthead } from '../masthead'
import { DEFAULT_MODE } from '../mode'
import type { Mode } from '../mode'
import { usePlayground } from '../playground'
import { Sidebar } from '../sidebar'
import { Snippet } from '../snippet'
import { useColorScheme } from '../theme'

export const App = (): ReactElement => {
  const playground = usePlayground()
  const scheme = useColorScheme()
  const [mode, setMode] = useState<Mode>(DEFAULT_MODE)
  const { state, spec, source, events, problem } = playground

  return (
    <div className="flex h-dvh flex-col bg-canvas text-ink">
      <Masthead
        mode={mode}
        scheme={scheme}
        onMode={setMode}
        onReset={playground.reset}
      />

      <div className="grid min-h-0 flex-1 grid-cols-1 grid-rows-[minmax(0,16rem)_minmax(0,1fr)] lg:grid-cols-[minmax(300px,23vw)_minmax(0,1fr)] lg:grid-rows-1">
        <Sidebar
          spec={
            <Controls
              state={state}
              update={playground.update}
              choosePreset={playground.choosePreset}
            />
          }
          events={
            <Events
              source={source}
              problem={problem}
              hint={presetOf(state.preset).hint}
              count={events.length}
              onChange={playground.changeSource}
            />
          }
        />

        <main className="flex min-h-0 min-w-0 flex-col">
          {mode === 'calendar' && (
            <Boundary key={JSON.stringify(spec)}>
              <Board
                spec={spec}
                events={events}
                locale={state.locale}
                density={state.density}
                style={state.style}
                onNavigate={playground.applySpec}
                onDensity={(density) => playground.update({ density })}
              />
            </Boundary>
          )}

          {mode === 'code' && (
            <Snippet
              spec={spec}
              events={events}
              locale={state.locale}
              hourHeight={hourHeightOf(state.density)}
              style={state.style}
            />
          )}
        </main>
      </div>
    </div>
  )
}

// apps/playground-vue/src/app/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { DEFAULT_MODE, hourHeightOf } from '@midstem/playground-core'
import type { Mode } from '@midstem/playground-core'

import Board from '../board/Board.vue'
import Masthead from '../masthead/Masthead.vue'
import { usePlayground } from '../playground/use-playground'
import Sidebar from '../sidebar/Sidebar.vue'
import Snippet from '../snippet/Snippet.vue'
import { useColorScheme } from '../theme/use-color-scheme'

const playground = usePlayground()
const scheme = useColorScheme()
const mode = ref<Mode>(DEFAULT_MODE)

const { state, range, events } = playground
const hourHeight = computed(() => hourHeightOf(state.value.density))
</script>

<template>
  <div class="flex h-dvh flex-col bg-canvas text-ink">
    <Masthead
      :mode="mode"
      :pinned-scheme="scheme.pinned.value"
      :resolved-scheme="scheme.resolved.value"
      @update:mode="mode = $event"
      @toggle-scheme="scheme.toggle"
      @reset="playground.reset"
    />

    <div
      class="grid min-h-0 flex-1 grid-cols-1 grid-rows-[minmax(0,16rem)_minmax(0,1fr)] lg:grid-cols-[minmax(300px,23vw)_minmax(0,1fr)] lg:grid-rows-1"
    >
      <Sidebar />

      <main class="flex min-h-0 min-w-0 flex-col">
        <Board
          v-if="mode === 'calendar'"
          :range="range"
          :events="events"
          :locale="state.locale"
          :density="state.density"
          :style="state.style"
          @navigate="playground.applyRange"
          @density="playground.update({ density: $event })"
        />

        <Snippet
          v-if="mode === 'code'"
          :range="range"
          :events="events"
          :locale="state.locale"
          :hour-height="hourHeight"
          :style="state.style"
        />
      </main>
    </div>
  </div>
</template>
