// apps/demo/src/snippet/index.tsx
import type {
  CalendarRange,
  EventInput,
  LocaleId
} from '@midstem/chronous-react'
import type { ReactElement } from 'react'

import { Code } from '../code'
import { SIMPLE_HINT, simpleBadgeOf, simpleOf } from '../simple'
import { isSimple } from '../style'
import type { Style } from '../style'
import type { EventData } from '../types'

import { FILE_NAME, SNIPPET_HINT, badgeOf } from './constants'
import { snippetOf } from './helpers'

type SnippetProps = {
  range: CalendarRange
  events: readonly EventInput<EventData>[]
  locale: LocaleId
  hourHeight: number
  style: Style
}

export const Snippet = ({
  range,
  events,
  locale,
  hourHeight,
  style
}: SnippetProps): ReactElement =>
  isSimple(style) ? (
    <Code
      fileName={FILE_NAME}
      badge={simpleBadgeOf(range.view, events.length)}
      hint={SIMPLE_HINT}
      source={simpleOf(range, events, locale, hourHeight)}
    />
  ) : (
    <Code
      fileName={FILE_NAME}
      badge={badgeOf(range.view, hourHeight, locale, events.length)}
      hint={SNIPPET_HINT}
      source={snippetOf(range, events, locale, hourHeight)}
    />
  )

// apps/playground-angular/src/snippet/snippet.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input
} from '@angular/core'
import type {
  CalendarRange,
  EventInput,
  LocaleId
} from '@midstem/chronous-angular'
import { isSimple } from '@midstem/playground-core'
import type { EventData, Style } from '@midstem/playground-core'

import { CodeComponent } from '../code/code.component'

import {
  FILE_NAME,
  SIMPLE_HINT,
  SNIPPET_HINT,
  badgeOf,
  simpleBadgeOf
} from './constants'
import { snippetOf } from './helpers'
import { simpleOf } from './simple'

@Component({
  selector: 'app-snippet',
  standalone: true,
  imports: [CodeComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <app-code
      [fileName]="fileName"
      [badge]="badge()"
      [hint]="hint()"
      [source]="source()"
    />
  `
})
export class SnippetComponent {
  readonly range = input.required<CalendarRange>()
  readonly events = input.required<readonly EventInput<EventData>[]>()
  readonly locale = input.required<LocaleId>()
  readonly hourHeight = input.required<number>()
  readonly style = input.required<Style>()

  readonly fileName = FILE_NAME

  readonly simple = computed(() => isSimple(this.style()))

  readonly hint = computed(() => (this.simple() ? SIMPLE_HINT : SNIPPET_HINT))

  readonly badge = computed(() =>
    this.simple()
      ? simpleBadgeOf(this.range().view, this.events().length)
      : badgeOf(
          this.range().view,
          this.hourHeight(),
          this.locale(),
          this.events().length
        )
  )

  readonly source = computed(() =>
    this.simple()
      ? simpleOf(this.range(), this.events(), this.locale(), this.hourHeight())
      : snippetOf(this.range(), this.events(), this.locale(), this.hourHeight())
  )
}
