// apps/playground-angular/src/allday/allday.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { CALENDAR_DIRECTIVES } from '@midstem/chronous-angular'
import {
  ALL_DAY_BAR_GAP,
  ALL_DAY_LABEL,
  ALL_DAY_LANE_HEIGHT,
  CONTINUES,
  MIN_LANES
} from '@midstem/playground-core'
import type { EventData } from '@midstem/playground-core'

@Component({
  selector: 'app-allday',
  standalone: true,
  imports: [CALENDAR_DIRECTIVES],
  host: {
    class: 'block'
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <chronous-all-day-row
      class="border-b border-line pt-0.5 pb-1.5"
      [laneHeight]="laneHeight"
      [minLanes]="minLanes"
    >
      <span
        chronousGutterCell
        class="block pt-1 pr-2 text-right text-[10px] text-faint"
      >
        {{ allDayLabel }}
      </span>

      <div
        *chronousAllDayEvents="let event; let bar = bar; gap: barGap"
        class="px-px py-px"
      >
        <span
          [class]="'flex h-full items-center truncate rounded-md bg-event-all-day px-2 text-[11px] font-medium text-event-all-day-ink'"
          [attr.title]="titleOf(event)"
        >
          {{ edge(bar.continuesBefore) }}
          {{ titleOf(event) }}
          {{ edge(bar.continuesAfter) }}
        </span>
      </div>
    </chronous-all-day-row>
  `
})
export class AlldayComponent {
  readonly laneHeight = ALL_DAY_LANE_HEIGHT
  readonly minLanes = MIN_LANES
  readonly barGap = ALL_DAY_BAR_GAP
  readonly allDayLabel = ALL_DAY_LABEL

  edge(shown: boolean): string {
    return shown ? CONTINUES : ''
  }

  titleOf(event: { id: string; data?: EventData }): string {
    return event.data?.title ?? event.id
  }
}

// apps/playground-vue/src/allday/AllDay.vue
<script setup lang="ts">
import { Calendar } from '@midstem/chronous-vue'
import {
  ALL_DAY_BAR_GAP,
  ALL_DAY_LABEL,
  ALL_DAY_LANE_HEIGHT,
  CONTINUES,
  MIN_LANES
} from '@midstem/playground-core'

const edge = (shown: boolean): string => (shown ? CONTINUES : '')
</script>

<template>
  <Calendar.AllDayRow
    class="border-b border-line pt-0.5 pb-1.5"
    :lane-height="ALL_DAY_LANE_HEIGHT"
    :min-lanes="MIN_LANES"
  >
    <template #gutterCell>
      <span class="block pt-1 pr-2 text-right text-[10px] text-faint">
        {{ ALL_DAY_LABEL }}
      </span>
    </template>

    <Calendar.AllDayEvents
      :gap="ALL_DAY_BAR_GAP"
      class="px-px py-px"
      v-slot="{ event, bar }"
    >
      <span
        :class="[
          'flex h-full items-center truncate rounded-md bg-event-all-day px-2 text-[11px] font-medium text-event-all-day-ink'
        ]"
        :title="event.data?.title ?? event.id"
      >
        {{ edge(bar.continuesBefore) }}
        {{ event.data?.title ?? event.id }}
        {{ edge(bar.continuesAfter) }}
      </span>
    </Calendar.AllDayEvents>
  </Calendar.AllDayRow>
</template>
