// packages/react/src/components/shared/all-day-events.tsx
import type { CalendarBar, CalendarEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useAllDayContext } from '../context'
import { percentOf, renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const GAP = 4

export type AllDayEventScope<TData> = {
  event: CalendarEntry<TData>
  bar: CalendarBar<TData>
}

export type AllDayEventsOwnProps<TData> = OwnProps<AllDayEventScope<TData>> & {
  gap?: number
}

export type AllDayEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, AllDayEventsOwnProps<TData>>

export const AllDayEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  gap = GAP,
  ...rest
}: AllDayEventsProps<TData, TTag>): ReactNode => {
  const { row, laneHeight } = useAllDayContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {row.bars.map((bar) => (
        <Tag
          key={`${bar.event.id}-${bar.startDay}`}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              left: `calc(${percentOf(bar.left)} + ${gap / 2}px)`,
              width: `calc(${percentOf(bar.width)} - ${gap}px)`,
              top: bar.lane * laneHeight,
              height: laneHeight
            },
            style
          )}
        >
          {renderSlot(children, { event: bar.event, bar }, bar.event.id)}
        </Tag>
      ))}
    </>
  )
}

// packages/angular/src/directives/shared/all-day-events.ts
import type { CalendarBar, CalendarEntry } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject,
  input
} from '@angular/core'

import { injectAllDayContext } from '../context'
import { contextOf, percentOf, pixelsOf, spanAttributes } from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'
import type { ViewStyle } from '../views'

const GAP = 4

const HALF = 2

export type AllDayEventScope<TData> = {
  event: CalendarEntry<TData>
  bar: CalendarBar<TData>
}

export type AllDayEventContext<TData> = ScopedContext<
  CalendarEntry<TData>,
  AllDayEventScope<TData>
>

@Directive({
  selector: '[chronousAllDayEvents]',
  exportAs: 'chronousAllDayEvents'
})
export class AllDayEventsDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: AllDayEventsDirective<TData>,
    _context: unknown
  ): _context is AllDayEventContext<TData> {
    return true
  }

  readonly gap = input(GAP, { alias: 'chronousAllDayEventsGap' })

  readonly #allDay = injectAllDayContext<TData>()

  readonly #container = inject(ViewContainerRef)

  readonly #template =
    inject<TemplateRef<AllDayEventContext<TData>>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #styleOf(bar: CalendarBar<TData>): ViewStyle {
    const gap = this.gap()

    return {
      position: 'absolute',
      left: `calc(${percentOf(bar.left)} + ${pixelsOf(gap / HALF)})`,
      width: `calc(${percentOf(bar.width)} - ${pixelsOf(gap)})`,
      top: pixelsOf(bar.lane * this.#allDay.laneHeight()),
      height: pixelsOf(this.#allDay.laneHeight())
    }
  }

  #render(): void {
    syncViews(this.#container, this.#template, this.#allDay.row().bars, {
      contextOf: (bar) => contextOf(bar.event, { event: bar.event, bar }),
      attributesOf: spanAttributes,
      styleOf: (bar) => this.#styleOf(bar)
    })
  }
}
