// packages/react/src/components/shared/header.tsx
import type { ReactNode } from 'react'
import { useCalendarContext } from '../context/calendar-context'
import { templateOf } from '../helpers'

export type HeaderProps = {
  children: ReactNode
  className?: string
  gutterWidth?: string
}

export const Header = ({
  children,
  className,
  gutterWidth = '3.25rem'
}: HeaderProps): ReactNode => {
  const { calendar } = useCalendarContext()

  return (
    <div
      className={className}
      style={{
        display: 'grid',
        gridTemplateColumns: templateOf(gutterWidth, calendar.days.length)
      }}
    >
      <div />
      {children}
    </div>
  )
}

// packages/angular/src/directives/shared/header.ts
import { Directive, computed } from '@angular/core'

import { injectCalendarContext } from '../context'
import { templateOf } from '../helpers'

@Directive({
  selector: '[chronousHeader]',
  exportAs: 'chronousHeader',
  host: {
    '[style.display]': '"grid"',
    '[style.gridTemplateColumns]': 'columns()'
  }
})
export class HeaderDirective {
  readonly #calendar = injectCalendarContext()

  readonly columns = computed(() =>
    templateOf(
      this.#calendar.gutterWidth(),
      this.#calendar.calendar().days.length
    )
  )
}
