// packages/react/src/components/month/month-weekdays.tsx
import type { CalendarDay } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import {
  WEEKDAY,
  labelOf,
  renderChildren,
  rowsWithDays,
  tagOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type MonthWeekdayScope<TData> = {
  day: CalendarDay<TData>
  weekdayLabel: string
}

export type MonthWeekdaysProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<MonthWeekdayScope<TData>>>

export const MonthWeekdays = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: MonthWeekdaysProps<TData, TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')
  const first = rowsWithDays(calendar)[0]

  return (
    <>
      {first.days.map((day) => {
        const weekdayLabel = labelOf(day.date, locale, WEEKDAY)

        return (
          <Tag key={day.date} {...rest} style={style}>
            {renderChildren(children, { day, weekdayLabel }, weekdayLabel)}
          </Tag>
        )
      })}
    </>
  )
}

// packages/angular/src/directives/month/month-weekdays.ts
import type { CalendarDay } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject
} from '@angular/core'

import { injectCalendarContext } from '../context'
import { WEEKDAY, contextOf, labelOf, rowsWithDays } from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'

export type MonthWeekdayScope<TData> = {
  day: CalendarDay<TData>
  weekdayLabel: string
}

export type MonthWeekdayContext<TData> = ScopedContext<
  CalendarDay<TData>,
  MonthWeekdayScope<TData>
>

@Directive({
  selector: '[chronousMonthWeekdays]',
  exportAs: 'chronousMonthWeekdays'
})
export class MonthWeekdaysDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: MonthWeekdaysDirective<TData>,
    _context: unknown
  ): _context is MonthWeekdayContext<TData> {
    return true
  }

  readonly #calendar = injectCalendarContext<TData>()

  readonly #container = inject(ViewContainerRef)

  readonly #template =
    inject<TemplateRef<MonthWeekdayContext<TData>>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #render(): void {
    const locale = this.#calendar.locale()
    const first = rowsWithDays(this.#calendar.calendar())[0]

    syncViews(this.#container, this.#template, first.days, {
      contextOf: (day) =>
        contextOf(day, {
          day,
          weekdayLabel: labelOf(day.date, locale, WEEKDAY)
        })
    })
  }
}
