// packages/react/src/components/month/month-all-day-events.tsx
import type { CalendarBar, CalendarEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useMonthRowContext } from '../context'
import {
  percentOf,
  renderChildren,
  styleOf,
  tagOf,
  visibleLanes
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const GAP = 4

const LANES_TOP_OFFSET = 28

const Z_INDEX = 1

export type MonthAllDayEventScope<TData> = {
  event: CalendarEntry<TData>
  bar: CalendarBar<TData>
}

export type MonthAllDayEventsOwnProps<TData> = OwnProps<
  MonthAllDayEventScope<TData>
> & {
  gap?: number
  lanesTopOffset?: number
}

export type MonthAllDayEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, MonthAllDayEventsOwnProps<TData>>

export const MonthAllDayEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  gap = GAP,
  lanesTopOffset = LANES_TOP_OFFSET,
  ...rest
}: MonthAllDayEventsProps<TData, TTag>): ReactNode => {
  const { row, maxLanes, laneHeight } = useMonthRowContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {visibleLanes(row.bars, maxLanes).map((bar) => (
        <Tag
          key={`${bar.event.id}-${bar.startDay}`}
          data-event-id={bar.event.id}
          data-continues-before={bar.continuesBefore}
          data-continues-after={bar.continuesAfter}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              left: `calc(${percentOf(bar.left)} + ${gap / 2}px)`,
              width: `calc(${percentOf(bar.width)} - ${gap}px)`,
              top: lanesTopOffset + bar.lane * laneHeight,
              height: laneHeight,
              zIndex: Z_INDEX
            },
            style
          )}
        >
          {renderChildren(children, { event: bar.event, bar }, bar.event.id)}
        </Tag>
      ))}
    </>
  )
}

// packages/angular/src/directives/month/month-all-day-events.ts
import type { CalendarBar, CalendarEntry } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject,
  input
} from '@angular/core'

import {
  contextOf,
  percentOf,
  pixelsOf,
  spanAttributes,
  visibleLanes
} from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'
import type { ViewStyle } from '../views'

import type { MonthRowScope } from './month-rows'

const GAP = 4

const HALF = 2

const LANES_TOP_OFFSET = 28

const Z_INDEX = '1'

export type MonthAllDayEventScope<TData> = {
  event: CalendarEntry<TData>
  bar: CalendarBar<TData>
}

export type MonthAllDayEventContext<TData> = ScopedContext<
  CalendarEntry<TData>,
  MonthAllDayEventScope<TData>
>

@Directive({
  selector: '[chronousMonthAllDayEvents]',
  exportAs: 'chronousMonthAllDayEvents'
})
export class MonthAllDayEventsDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: MonthAllDayEventsDirective<TData>,
    _context: unknown
  ): _context is MonthAllDayEventContext<TData> {
    return true
  }

  readonly monthRow = input.required<MonthRowScope<TData>>({
    alias: 'chronousMonthAllDayEvents'
  })

  readonly gap = input(GAP, { alias: 'chronousMonthAllDayEventsGap' })

  readonly lanesTopOffset = input(LANES_TOP_OFFSET, {
    alias: 'chronousMonthAllDayEventsLanesTopOffset'
  })

  readonly #container = inject(ViewContainerRef)

  readonly #template =
    inject<TemplateRef<MonthAllDayEventContext<TData>>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #styleOf(bar: CalendarBar<TData>): ViewStyle {
    const gap = this.gap()
    const { laneHeight } = this.monthRow()

    return {
      position: 'absolute',
      left: `calc(${percentOf(bar.left)} + ${pixelsOf(gap / HALF)})`,
      width: `calc(${percentOf(bar.width)} - ${pixelsOf(gap)})`,
      top: pixelsOf(this.lanesTopOffset() + bar.lane * laneHeight),
      height: pixelsOf(laneHeight),
      'z-index': Z_INDEX
    }
  }

  #render(): void {
    const { row, maxLanes } = this.monthRow()

    syncViews(
      this.#container,
      this.#template,
      visibleLanes(row.bars, maxLanes),
      {
        contextOf: (bar) => contextOf(bar.event, { event: bar.event, bar }),
        attributesOf: spanAttributes,
        styleOf: (bar) => this.#styleOf(bar)
      }
    )
  }
}
