// packages/react/src/components/month/month-days.tsx
import type { CalendarBar, CalendarBox, CalendarDay } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import {
  MonthDayProvider,
  useCalendarContext,
  useMonthRowContext
} from '../context'
import type { MonthDayContextValue } from '../context'
import {
  DAY_NUMBER,
  hiddenLanes,
  labelOf,
  laneCount,
  renderChildren,
  rowBarsByDay,
  tagOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type MonthDayScope<TData> = {
  day: CalendarDay<TData>
  boxes: CalendarBox<TData>[]
  bars: CalendarBar<TData>[]
  hiddenBars: CalendarBar<TData>[]
  dayLabel: string
  inCurrentPeriod: boolean
  lanes: number
}

export type MonthDaysProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<MonthDayScope<TData>>>

export const MonthDays = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: MonthDaysProps<TData, TTag>): ReactNode => {
  const { locale } = useCalendarContext<TData>()
  const { row, days, maxLanes } = useMonthRowContext<TData>()
  const Tag = tagOf(as, 'div')
  const barsByDay = rowBarsByDay(row, days.length)

  return (
    <>
      {days.map((day, index) => {
        const dayLabel = labelOf(day.date, locale, DAY_NUMBER)
        const bars = barsByDay[index]
        const value: MonthDayContextValue<TData> = {
          day,
          boxes: day.boxes,
          bars,
          hiddenBars: hiddenLanes(bars, maxLanes)
        }

        return (
          <MonthDayProvider key={day.date} value={value}>
            <Tag
              data-date={day.date}
              data-in-current-period={day.inCurrentPeriod}
              {...rest}
              style={style}
            >
              {renderChildren(
                children,
                {
                  ...value,
                  dayLabel,
                  inCurrentPeriod: day.inCurrentPeriod,
                  lanes: laneCount(row.lanes, maxLanes)
                },
                dayLabel
              )}
            </Tag>
          </MonthDayProvider>
        )
      })}
    </>
  )
}

// packages/angular/src/directives/month/month-days.ts
import type { CalendarBar, CalendarBox, CalendarDay } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject,
  input
} from '@angular/core'

import { injectCalendarContext } from '../context'
import {
  DAY_NUMBER,
  contextOf,
  dayAttributes,
  hiddenLanes,
  labelOf,
  laneCount,
  rowBarsByDay
} from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'

import type { MonthRowScope } from './month-rows'

export type MonthDayScope<TData> = {
  day: CalendarDay<TData>
  boxes: CalendarBox<TData>[]
  bars: CalendarBar<TData>[]
  hiddenBars: CalendarBar<TData>[]
  dayLabel: string
  inCurrentPeriod: boolean
  lanes: number
}

export type MonthDayContext<TData> = ScopedContext<
  CalendarDay<TData>,
  MonthDayScope<TData>
>

@Directive({ selector: '[chronousMonthDays]', exportAs: 'chronousMonthDays' })
export class MonthDaysDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: MonthDaysDirective<TData>,
    _context: unknown
  ): _context is MonthDayContext<TData> {
    return true
  }

  readonly monthRow = input.required<MonthRowScope<TData>>({
    alias: 'chronousMonthDays'
  })

  readonly #calendar = injectCalendarContext<TData>()

  readonly #container = inject(ViewContainerRef)

  readonly #template = inject<TemplateRef<MonthDayContext<TData>>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #render(): void {
    const locale = this.#calendar.locale()
    const { row, days, maxLanes } = this.monthRow()
    const barsByDay = rowBarsByDay(row, days.length)

    syncViews(this.#container, this.#template, days, {
      contextOf: (day, index) => {
        const bars = barsByDay[index]

        return contextOf(day, {
          day,
          boxes: day.boxes,
          bars,
          hiddenBars: hiddenLanes(bars, maxLanes),
          dayLabel: labelOf(day.date, locale, DAY_NUMBER),
          inCurrentPeriod: day.inCurrentPeriod,
          lanes: laneCount(row.lanes, maxLanes)
        })
      },
      attributesOf: dayAttributes
    })
  }
}
