// packages/react/src/components/month/month-grid.tsx
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import type { CalendarContextValue } from '../context'
import { renderChildren, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type MonthGridProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<CalendarContextValue<TData>>>

export const MonthGrid = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: MonthGridProps<TData, TTag>): ReactNode => {
  const scope = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <Tag
      {...rest}
      style={styleOf(
        { display: 'flex', flexDirection: 'column', minHeight: '100%' },
        style
      )}
    >
      {renderChildren(children, scope, null)}
    </Tag>
  )
}

// packages/svelte/src/components/month/MonthGrid.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import { useCalendarContext } from '../context'
  import type { CalendarContextValue } from '../context'
  import { styleText } from '../helpers'
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[CalendarContextValue<TData>]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const scope = useCalendarContext<TData>()
</script>

<svelte:element
  this={as}
  {...rest}
  style={styleText(
    { display: 'flex', flexDirection: 'column', minHeight: '100%' },
    style
  )}
  >{#if children}{@render children(scope)}{/if}</svelte:element
>
