// apps/playground-react/src/main.tsx
import 'temporal-polyfill/global'

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'

import { startEmbedBridge } from '@midstem/playground-core'

import { App } from './app'
import { Boundary } from './boundary'
import { ROOT_ID } from './constants'

import './styles.css'

startEmbedBridge()

const container = document.getElementById(ROOT_ID)

if (container)
  createRoot(container).render(
    <StrictMode>
      <Boundary>
        <App />
      </Boundary>
    </StrictMode>
  )

// apps/playground-angular/src/main.ts
import 'temporal-polyfill/global'

import { provideZonelessChangeDetection } from '@angular/core'
import { bootstrapApplication } from '@angular/platform-browser'
import { startEmbedBridge } from '@midstem/playground-core'

import { AppComponent } from './app/app.component'
import './styles.css'

startEmbedBridge()

bootstrapApplication(AppComponent, {
  providers: [provideZonelessChangeDetection()]
}).catch((error: unknown) => {
  // eslint-disable-next-line no-console
  console.error(error)
})
