// apps/playground-vue/src/snippet/Snippet.vue
<script setup lang="ts">
import { computed } from 'vue'
import type {
  CalendarRange,
  EventInput,
  LocaleId
} from '@midstem/chronous-vue'
import { isSimple } from '@midstem/playground-core'
import type { EventData, Style } from '@midstem/playground-core'

import Code from '../code/Code.vue'

import {
  FILE_NAME,
  SIMPLE_HINT,
  SNIPPET_HINT,
  badgeOf,
  simpleBadgeOf
} from './constants'
import { snippetOf } from './helpers'
import { simpleOf } from './simple'

const props = defineProps<{
  range: CalendarRange
  events: readonly EventInput<EventData>[]
  locale: LocaleId
  hourHeight: number
  style: Style
}>()

const simple = computed(() => isSimple(props.style))

const hint = computed(() => (simple.value ? SIMPLE_HINT : SNIPPET_HINT))

const badge = computed(() =>
  simple.value
    ? simpleBadgeOf(props.range.view, props.events.length)
    : badgeOf(
        props.range.view,
        props.hourHeight,
        props.locale,
        props.events.length
      )
)

const source = computed(() =>
  simple.value
    ? simpleOf(props.range, props.events, props.locale, props.hourHeight)
    : snippetOf(props.range, props.events, props.locale, props.hourHeight)
)
</script>

<template>
  <Code
    :file-name="FILE_NAME"
    :badge="badge"
    :hint="hint"
    :source="source"
  />
</template>

// apps/demo/src/snippet/index.tsx
import type {
  CalendarRange,
  EventInput,
  LocaleId
} from '@midstem/chronous-react'
import type { ReactElement } from 'react'

import { Code } from '../code'
import { SIMPLE_HINT, simpleBadgeOf, simpleOf } from '../simple'
import { isSimple } from '../style'
import type { Style } from '../style'
import type { EventData } from '../types'

import { FILE_NAME, SNIPPET_HINT, badgeOf } from './constants'
import { snippetOf } from './helpers'

type SnippetProps = {
  range: CalendarRange
  events: readonly EventInput<EventData>[]
  locale: LocaleId
  hourHeight: number
  style: Style
}

export const Snippet = ({
  range,
  events,
  locale,
  hourHeight,
  style
}: SnippetProps): ReactElement =>
  isSimple(style) ? (
    <Code
      fileName={FILE_NAME}
      badge={simpleBadgeOf(range.view, events.length)}
      hint={SIMPLE_HINT}
      source={simpleOf(range, events, locale, hourHeight)}
    />
  ) : (
    <Code
      fileName={FILE_NAME}
      badge={badgeOf(range.view, hourHeight, locale, events.length)}
      hint={SNIPPET_HINT}
      source={snippetOf(range, events, locale, hourHeight)}
    />
  )
