// packages/react/src/components/agenda/agenda-days.tsx
import type { ElementType, ReactNode } from 'react'

import { AgendaDayProvider, useCalendarContext } from '../context'
import type { AgendaDayContextValue } from '../context'
import {
  DAY_NUMBER,
  MONTH,
  WEEKDAY,
  barsByDay,
  labelOf,
  renderSlot,
  tagOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type AgendaDayScope<TData> = AgendaDayContextValue<TData> & {
  weekday: string
  dayNumber: string
  month: string
}

export type AgendaDaysOwnProps<TData> = OwnProps<AgendaDayScope<TData>> & {
  showEmpty?: boolean
}

export type AgendaDaysProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, AgendaDaysOwnProps<TData>>

export const AgendaDays = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  showEmpty = false,
  ...rest
}: AgendaDaysProps<TData, TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')
  const bars = barsByDay(calendar)

  return (
    <>
      {calendar.days.map((day, index) => {
        const onDay = bars[index]

        if (!showEmpty && onDay.length === 0 && day.boxes.length === 0) {
          return null
        }

        const value: AgendaDayContextValue<TData> = {
          day,
          bars: onDay,
          boxes: day.boxes
        }

        const scope: AgendaDayScope<TData> = {
          ...value,
          weekday: labelOf(day.date, locale, WEEKDAY),
          dayNumber: labelOf(day.date, locale, DAY_NUMBER),
          month: labelOf(day.date, locale, MONTH)
        }

        return (
          <AgendaDayProvider key={day.date} value={value}>
            <Tag {...rest} style={style}>
              {renderSlot(children, scope, scope.dayNumber)}
            </Tag>
          </AgendaDayProvider>
        )
      })}
    </>
  )
}

// packages/svelte/src/components/agenda/AgendaDays.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import { useCalendarContext } from '../context'
  import type { AgendaDayScope } from '../types'
  import { barsByDay } from '../helpers'
  import AgendaDay from './AgendaDay.svelte'
  let {
    as = 'div',
    children,
    style,
    showEmptyDays = false,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[AgendaDayScope<TData>]>
    style?: string | Record<string, string | number>
    showEmptyDays?: boolean
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext<TData>()
  let bars = $derived(barsByDay(context.calendar))
</script>

{#each context.calendar.days as day, index (day.date)}
  {@const dayBars = bars[index] ?? []}
  {#if showEmptyDays || dayBars.length > 0 || day.boxes.length > 0}
    <AgendaDay {day} bars={dayBars} {as} {children} {style} {...rest} />
  {/if}
{/each}
