// packages/react/src/components/agenda/agenda-timed-events.tsx
import type { CalendarBox, TimedEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useAgendaDayContext, useCalendarContext } from '../context'
import { rangeOf, renderChildren, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type AgendaTimedEventScope<TData> = {
  event: TimedEntry<TData>
  box: CalendarBox<TData>
  timeRangeLabel: string
}

export type AgendaTimedEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<AgendaTimedEventScope<TData>>>

export const AgendaTimedEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: AgendaTimedEventsProps<TData, TTag>): ReactNode => {
  const { locale } = useCalendarContext()
  const { boxes } = useAgendaDayContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {boxes.map((box) => {
        const timeRangeLabel = rangeOf(box.start, box.end, locale)

        return (
          <Tag
            key={`${box.event.id}-${box.startMinute}`}
            data-event-id={box.event.id}
            data-continues-before={box.continuesBefore}
            data-continues-after={box.continuesAfter}
            {...rest}
            style={style}
          >
            {renderChildren(
              children,
              { event: box.event, box, timeRangeLabel },
              timeRangeLabel
            )}
          </Tag>
        )
      })}
    </>
  )
}

// packages/svelte/src/components/agenda/AgendaTimedEvents.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarBox, TimedEntry } from '../../engine.js'
  import { useAgendaDayContext, useCalendarContext } from '../context'
  import { rangeOf, styleText } from '../helpers'
  type AgendaTimedEventScope<T> = {
    event: TimedEntry<T>
    box: CalendarBox<T>
    timeRangeLabel: string
  }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[AgendaTimedEventScope<TData>]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const calendarContext = useCalendarContext()
  const dayContext = useAgendaDayContext<TData>()
</script>

{#each dayContext.boxes as box (`${box.event.id}-${box.startMinute}`)}
  {@const timeRangeLabel = rangeOf(box.start, box.end, calendarContext.locale)}
  <svelte:element
    this={as}
    data-event-id={box.event.id}
    data-continues-before={box.continuesBefore}
    data-continues-after={box.continuesAfter}
    {...rest}
    style={styleText({}, style)}
  >
    {#if children}
      {@render children({
        event: box.event,
        box,
        timeRangeLabel
      })}
    {:else}
      {timeRangeLabel}
    {/if}
  </svelte:element>
{/each}
