// packages/svelte/src/components/slotted/DayColumns.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import { useCalendarContext } from '../context'
  import DayColumn from './DayColumn.svelte'
  import type { DayColumnContextValue } from '../context'
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[DayColumnContextValue<TData>]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext<TData>()
</script>

{#each context.calendar.days as day (day.date)}
  <DayColumn {day} {as} {children} {style} {...rest} />
{/each}

// packages/react/src/components/slotted/day-columns.tsx
import type { ElementType, ReactNode } from 'react'

import {
  DayColumnProvider,
  useCalendarContext,
  useTimeGridContext
} from '../context'
import type { DayColumnContextValue } from '../context'
import { renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type DayColumnsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<DayColumnContextValue<TData>>>

export const DayColumns = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: DayColumnsProps<TData, TTag>): ReactNode => {
  const { calendar } = useCalendarContext<TData>()
  const { dayHeight } = useTimeGridContext()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {calendar.days.map((day) => (
        <DayColumnProvider key={day.date} value={{ day }}>
          <Tag
            {...rest}
            style={styleOf({ position: 'relative', height: dayHeight }, style)}
          >
            {renderSlot(children, { day }, null)}
          </Tag>
        </DayColumnProvider>
      ))}
    </>
  )
}
