// packages/svelte/src/components/slotted/TimeSlots.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { CalendarSlot } from '../../engine.js'
  import { useDayColumnContext } from '../context'
  import { minutePercentOf, styleText } from '../helpers'
  type TimeSlotScope = { slot: CalendarSlot; minuteOfDay: number }
  let {
    as = 'span',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[TimeSlotScope]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useDayColumnContext()
</script>

{#each context.day.slots as slot (slot.minuteOfDay)}<svelte:element
    this={as}
    {...rest}
    style={styleText(
      {
        position: 'absolute',
        left: 0,
        right: 0,
        top: minutePercentOf(slot.minuteOfDay)
      },
      style
    )}
    >{#if children}{@render children({
        slot,
        minuteOfDay: slot.minuteOfDay
      })}{/if}</svelte:element
  >{/each}

// packages/react/src/components/slotted/time-slots.tsx
import type { CalendarSlot } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useDayColumnContext } from '../context'
import { minutePercentOf, renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type TimeSlotScope = {
  slot: CalendarSlot
  minuteOfDay: number
}

export type TimeSlotsProps<TTag extends ElementType = 'span'> =
  PolymorphicProps<TTag, OwnProps<TimeSlotScope>>

export const TimeSlots = <TTag extends ElementType = 'span'>({
  as,
  children,
  style,
  ...rest
}: TimeSlotsProps<TTag>): ReactNode => {
  const { day } = useDayColumnContext()
  const Tag = tagOf(as, 'span')

  return (
    <>
      {day.slots.map((slot) => (
        <Tag
          key={slot.minuteOfDay}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              left: 0,
              right: 0,
              top: minutePercentOf(slot.minuteOfDay)
            },
            style
          )}
        >
          {renderSlot(children, { slot, minuteOfDay: slot.minuteOfDay }, null)}
        </Tag>
      ))}
    </>
  )
}
