// packages/angular/src/directives/slotted/timed-events.ts
import type { CalendarBox, CalendarDay, TimedEntry } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject,
  input
} from '@angular/core'

import { contextOf, percentOf, pixelsOf, spanAttributes } from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'
import type { ViewStyle } from '../views'

const MIN_HEIGHT = 22

const GAP = 3

export type TimedEventScope<TData> = {
  event: TimedEntry<TData>
  box: CalendarBox<TData>
}

export type TimedEventContext<TData> = ScopedContext<
  TimedEntry<TData>,
  TimedEventScope<TData>
>

@Directive({
  selector: '[chronousTimedEvents]',
  exportAs: 'chronousTimedEvents'
})
export class TimedEventsDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: TimedEventsDirective<TData>,
    _context: unknown
  ): _context is TimedEventContext<TData> {
    return true
  }

  readonly day = input.required<CalendarDay<TData>>({
    alias: 'chronousTimedEvents'
  })

  readonly minHeight = input(MIN_HEIGHT, {
    alias: 'chronousTimedEventsMinHeight'
  })

  readonly gap = input(GAP, { alias: 'chronousTimedEventsGap' })

  readonly #container = inject(ViewContainerRef)

  readonly #template =
    inject<TemplateRef<TimedEventContext<TData>>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #styleOf(box: CalendarBox<TData>): ViewStyle {
    return {
      position: 'absolute',
      overflow: 'hidden',
      top: percentOf(box.top),
      height: percentOf(box.height),
      left: percentOf(box.left),
      width: `calc(${percentOf(box.width)} - ${pixelsOf(this.gap())})`,
      'min-height': pixelsOf(this.minHeight())
    }
  }

  #render(): void {
    syncViews(this.#container, this.#template, this.day().boxes, {
      contextOf: (box) => contextOf(box.event, { event: box.event, box }),
      attributesOf: spanAttributes,
      styleOf: (box) => this.#styleOf(box)
    })
  }
}

// packages/react/src/components/slotted/timed-events.tsx
import type { CalendarBox, TimedEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useDayColumnContext } from '../context'
import { percentOf, renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const MIN_HEIGHT = 22

const GAP = 3

export type TimedEventScope<TData> = {
  event: TimedEntry<TData>
  box: CalendarBox<TData>
}

export type TimedEventsOwnProps<TData> = OwnProps<TimedEventScope<TData>> & {
  minHeight?: number
  gap?: number
}

export type TimedEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, TimedEventsOwnProps<TData>>

export const TimedEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  minHeight = MIN_HEIGHT,
  gap = GAP,
  ...rest
}: TimedEventsProps<TData, TTag>): ReactNode => {
  const { day } = useDayColumnContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {day.boxes.map((box) => (
        <Tag
          key={`${box.event.id}-${box.startMinute}`}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              overflow: 'hidden',
              top: percentOf(box.top),
              height: percentOf(box.height),
              left: percentOf(box.left),
              width: `calc(${percentOf(box.width)} - ${gap}px)`,
              minHeight
            },
            style
          )}
        >
          {renderSlot(children, { event: box.event, box }, box.event.id)}
        </Tag>
      ))}
    </>
  )
}
