// packages/angular/src/directives/slotted/time-slots.ts
import type { CalendarDay, CalendarSlot } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject,
  input
} from '@angular/core'

import { contextOf, minutePercentOf } from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'

export type TimeSlotScope = {
  slot: CalendarSlot
  minuteOfDay: number
}

export type TimeSlotContext = ScopedContext<CalendarSlot, TimeSlotScope>

@Directive({ selector: '[chronousTimeSlots]', exportAs: 'chronousTimeSlots' })
export class TimeSlotsDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: TimeSlotsDirective<TData>,
    _context: unknown
  ): _context is TimeSlotContext {
    return true
  }

  readonly day = input.required<CalendarDay<TData>>({
    alias: 'chronousTimeSlots'
  })

  readonly #container = inject(ViewContainerRef)

  readonly #template = inject<TemplateRef<TimeSlotContext>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #render(): void {
    syncViews(this.#container, this.#template, this.day().slots, {
      contextOf: (slot) =>
        contextOf(slot, { slot, minuteOfDay: slot.minuteOfDay }),
      styleOf: (slot) => ({
        position: 'absolute',
        left: '0',
        right: '0',
        top: minutePercentOf(slot.minuteOfDay)
      })
    })
  }
}

// packages/react/src/components/slotted/time-slots.tsx
import type { CalendarSlot } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useDayColumnContext } from '../context'
import { minutePercentOf, renderSlot, styleOf, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type TimeSlotScope = {
  slot: CalendarSlot
  minuteOfDay: number
}

export type TimeSlotsProps<TTag extends ElementType = 'span'> =
  PolymorphicProps<TTag, OwnProps<TimeSlotScope>>

export const TimeSlots = <TTag extends ElementType = 'span'>({
  as,
  children,
  style,
  ...rest
}: TimeSlotsProps<TTag>): ReactNode => {
  const { day } = useDayColumnContext()
  const Tag = tagOf(as, 'span')

  return (
    <>
      {day.slots.map((slot) => (
        <Tag
          key={slot.minuteOfDay}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              left: 0,
              right: 0,
              top: minutePercentOf(slot.minuteOfDay)
            },
            style
          )}
        >
          {renderSlot(children, { slot, minuteOfDay: slot.minuteOfDay }, null)}
        </Tag>
      ))}
    </>
  )
}
