// packages/svelte/src/components/shared/AllDayRow.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import { provideAllDay, useCalendarContext } from '../context'
  import type { AllDayContextValue } from '../context'
  import { styleText, templateOf } from '../helpers'
  let {
    as = 'div',
    children,
    style,
    laneHeight = 24,
    minLanes = 0,
    gutterCell,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[AllDayContextValue<TData>]>
    style?: string | Record<string, string | number>
    laneHeight?: number
    minLanes?: number
    gutterCell?: Snippet
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext<TData>()
  let row = $derived(context.calendar.rows[0])
  let lanes = $derived(Math.max(row.lanes, minLanes))
  const scope = {
    get row() {
      return row
    },
    get laneHeight() {
      return laneHeight
    },
    get lanes() {
      return lanes
    }
  }
  provideAllDay(scope)
  let css = $derived(
    styleText(
      {
        display: 'grid',
        gridTemplateColumns: templateOf(
          context.gutterWidth,
          context.calendar.days.length
        )
      },
      style
    )
  )
</script>

{#if lanes > 0}
  <svelte:element this={as} {...rest} style={css}>
    <div>
      {#if gutterCell}{@render gutterCell()}{/if}
    </div>
    <div
      style={`grid-column:2 / -1;position:relative;height:${lanes * laneHeight}px`}
    >
      {#if children}{@render children(scope)}{/if}
    </div>
  </svelte:element>
{/if}

// packages/react/src/components/shared/all-day-row.tsx
import type { ElementType, ReactNode } from 'react'

import { AllDayProvider, useCalendarContext } from '../context'
import type { AllDayContextValue } from '../context'
import { renderChildren, styleOf, tagOf, templateOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const LANE_HEIGHT = 24

const MIN_LANES = 0

export type AllDayRowOwnProps<TData> = OwnProps<AllDayContextValue<TData>> & {
  laneHeight?: number
  minLanes?: number
  gutterCell?: ReactNode
}

export type AllDayRowProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, AllDayRowOwnProps<TData>>

export const AllDayRow = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  laneHeight = LANE_HEIGHT,
  minLanes = MIN_LANES,
  gutterCell = null,
  ...rest
}: AllDayRowProps<TData, TTag>): ReactNode => {
  const { calendar, gutterWidth } = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')
  const row = calendar.rows[0]
  const lanes = Math.max(row.lanes, minLanes)

  if (lanes === 0) return null

  const scope: AllDayContextValue<TData> = { row, laneHeight, lanes }

  return (
    <AllDayProvider value={scope}>
      <Tag
        {...rest}
        style={styleOf(
          {
            display: 'grid',
            gridTemplateColumns: templateOf(gutterWidth, calendar.days.length)
          },
          style
        )}
      >
        <div>{gutterCell}</div>
        <div
          style={{
            gridColumn: '2 / -1',
            position: 'relative',
            height: lanes * laneHeight
          }}
        >
          {renderChildren(children, scope, null)}
        </div>
      </Tag>
    </AllDayProvider>
  )
}
