// packages/angular/src/directives/shared/day-headings.ts
import type { CalendarDay, IsoDate } from '@midstem/chronous'
import {
  Directive,
  TemplateRef,
  ViewContainerRef,
  effect,
  inject
} from '@angular/core'

import { injectCalendarContext } from '../context'
import {
  DAY_NUMBER,
  WEEKDAY,
  contextOf,
  dayAttributes,
  labelOf
} from '../helpers'
import type { ScopedContext } from '../types'
import { syncViews } from '../views'

export type DayHeadingScope<TData> = {
  day: CalendarDay<TData>
  date: IsoDate
  weekdayLabel: string
  dayLabel: string
  inCurrentPeriod: boolean
}

export type DayHeadingContext<TData> = ScopedContext<
  CalendarDay<TData>,
  DayHeadingScope<TData>
>

@Directive({
  selector: '[chronousDayHeadings]',
  exportAs: 'chronousDayHeadings'
})
export class DayHeadingsDirective<TData> {
  static ngTemplateContextGuard<TData>(
    _directive: DayHeadingsDirective<TData>,
    _context: unknown
  ): _context is DayHeadingContext<TData> {
    return true
  }

  readonly #calendar = injectCalendarContext<TData>()

  readonly #container = inject(ViewContainerRef)

  readonly #template =
    inject<TemplateRef<DayHeadingContext<TData>>>(TemplateRef)

  constructor() {
    effect(() => this.#render())
  }

  #render(): void {
    const locale = this.#calendar.locale()

    syncViews(this.#container, this.#template, this.#calendar.calendar().days, {
      contextOf: (day) =>
        contextOf(day, {
          day,
          date: day.date,
          weekdayLabel: labelOf(day.date, locale, WEEKDAY),
          dayLabel: labelOf(day.date, locale, DAY_NUMBER),
          inCurrentPeriod: day.inCurrentPeriod
        }),
      attributesOf: dayAttributes
    })
  }
}

// packages/react/src/components/shared/day-headings.tsx
import type { CalendarDay, IsoDate } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import { DAY_NUMBER, WEEKDAY, labelOf, renderChildren, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type DayHeadingScope<TData> = {
  day: CalendarDay<TData>
  date: IsoDate
  weekdayLabel: string
  dayLabel: string
  inCurrentPeriod: boolean
}

export type DayHeadingsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<DayHeadingScope<TData>>>

export const DayHeadings = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: DayHeadingsProps<TData, TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {calendar.days.map((day) => {
        const weekdayLabel = labelOf(day.date, locale, WEEKDAY)
        const dayLabel = labelOf(day.date, locale, DAY_NUMBER)

        return (
          <Tag
            key={day.date}
            data-date={day.date}
            data-in-current-period={day.inCurrentPeriod}
            {...rest}
            style={style}
          >
            {renderChildren(
              children,
              {
                day,
                date: day.date,
                weekdayLabel,
                dayLabel,
                inCurrentPeriod: day.inCurrentPeriod
              },
              `${weekdayLabel} ${dayLabel}`
            )}
          </Tag>
        )
      })}
    </>
  )
}
