// packages/svelte/src/components/shared/Root.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarRange, EventInput, LocaleId } from '../../engine.js'
  import { resultOf } from '../../calendar/helpers'
  import type { CalendarError } from '../../calendar/types'
  import { provideCalendar } from '../context'
  import { GUTTER_WIDTH, styleText } from '../helpers'
  import type { CalendarContextValue } from '../context'
  let {
    as = 'div',
    range,
    events,
    locale = 'en-US',
    gutterWidth = GUTTER_WIDTH,
    children,
    renderError,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    range: CalendarRange
    events: readonly EventInput<TData>[]
    locale?: LocaleId
    gutterWidth?: string
    children?: Snippet<[CalendarContextValue<TData>]>
    renderError?: Snippet<[CalendarError]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  let result = $derived(resultOf(range, events))
  const raise = (error: CalendarError): never => {
    throw error
  }
  const context: CalendarContextValue<TData> = {
    get calendar() {
      if (!result.calendar) throw result.error
      return result.calendar
    },
    get range() {
      return range
    },
    get locale() {
      return locale
    },
    get gutterWidth() {
      return gutterWidth
    }
  }
  provideCalendar(context)
</script>

<svelte:element this={as} {...rest} style={styleText({}, style)}>
  {#if result.error}
    {#if renderError}{@render renderError(result.error)}{:else}{raise(
        result.error
      )}{/if}
  {:else if children}
    {@render children(context)}
  {/if}
</svelte:element>

// packages/react/src/components/shared/root.tsx
import type { EventInput, LocaleId, CalendarRange } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendar } from '#src/calendar'
import type { CalendarError } from '#src/calendar'

import { CalendarProvider } from '../context'
import type { CalendarContextValue } from '../context'
import { GUTTER_WIDTH, renderChildren, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const LOCALE: LocaleId = 'en-US'

export type RootOwnProps<TData> = OwnProps<CalendarContextValue<TData>> & {
  range: CalendarRange
  events: readonly EventInput<TData>[]
  locale?: LocaleId
  gutterWidth?: string
  renderError?: (error: CalendarError) => ReactNode
}

export type RootProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, RootOwnProps<TData>>

export const Root = <TData, TTag extends ElementType = 'div'>({
  as,
  range,
  events,
  locale = LOCALE,
  gutterWidth = GUTTER_WIDTH,
  children,
  style,
  renderError,
  ...rest
}: RootProps<TData, TTag>): ReactNode => {
  const { calendar, error } = useCalendar(range, events)
  const Tag = tagOf(as, 'div')

  if (error) {
    if (!renderError) throw error

    return (
      <Tag {...rest} style={style}>
        {renderError(error)}
      </Tag>
    )
  }

  const scope: CalendarContextValue<TData> = {
    calendar,
    range,
    locale,
    gutterWidth
  }

  return (
    <Tag {...rest} style={style}>
      <CalendarProvider value={scope}>
        {renderChildren(children, scope, null)}
      </CalendarProvider>
    </Tag>
  )
}
