// packages/svelte/src/components/shared/Toolbar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { CalendarRange, ViewKind } from '../../engine.js'
  import { calendarNavigation } from '../../navigation'
  import { useCalendarContext } from '../context'
  import { styleText } from '../helpers'
  import { titleOf } from './helpers'
  import type { ToolbarScope } from '../types'
  let {
    as = 'div',
    children,
    onNavigate,
    views = ['day', 'week', 'month', 'agenda'],
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[ToolbarScope]>
    onNavigate: (range: CalendarRange) => void
    views?: readonly ViewKind[]
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext()
  let range = $derived(context.range)
  let navigation = $derived(calendarNavigation(range))
  let title = $derived(titleOf(range, context.locale))
</script>

<svelte:element this={as} {...rest} style={styleText({}, style)}>
  {#if children}{@render children({
      navigation,
      range,
      title,
      goTo: onNavigate
    })}{:else}
    <button
      type="button"
      aria-label="Previous period"
      disabled={!navigation.prev}
      onclick={() => navigation.prev && onNavigate(navigation.prev)}>‹</button
    >
    <button
      type="button"
      disabled={!navigation.today}
      onclick={() => navigation.today && onNavigate(navigation.today())}
      >Today</button
    >
    <button
      type="button"
      aria-label="Next period"
      disabled={!navigation.next}
      onclick={() => navigation.next && onNavigate(navigation.next)}>›</button
    >
    <span>{title}</span>
    {#each views as view}<button
        type="button"
        aria-pressed={view === range.view}
        onclick={() => onNavigate(navigation.withView(view))}>{view}</button
      >{/each}
  {/if}
</svelte:element>

// packages/react/src/components/shared/toolbar.tsx
import type { CalendarRange, ViewKind } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarNavigation } from '#src/navigation'
import type { CalendarNavigation } from '#src/navigation'

import { useCalendarContext } from '../context'
import { renderChildren, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'
import { titleOf } from './helpers'

const VIEWS: ViewKind[] = ['day', 'week', 'month', 'agenda']

export type ToolbarScope = {
  navigation: CalendarNavigation
  range: CalendarRange
  title: string
  goTo: (range: CalendarRange) => void
}

export type ToolbarOwnProps = OwnProps<ToolbarScope> & {
  onNavigate: (range: CalendarRange) => void
  views?: readonly ViewKind[]
}

export type ToolbarProps<TTag extends ElementType = 'div'> = PolymorphicProps<
  TTag,
  ToolbarOwnProps
>

export const Toolbar = <TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  onNavigate,
  views = VIEWS,
  ...rest
}: ToolbarProps<TTag>): ReactNode => {
  const { range, locale } = useCalendarContext()
  const navigation = useCalendarNavigation(range)
  const Tag = tagOf(as, 'div')
  const title = titleOf(range, locale)
  const { prev, next, today } = navigation

  if (children !== undefined) {
    return (
      <Tag {...rest} style={style}>
        {renderChildren(
          children,
          { navigation, range, title, goTo: onNavigate },
          null
        )}
      </Tag>
    )
  }

  return (
    <Tag {...rest} style={style}>
      <button
        type="button"
        aria-label="Previous period"
        disabled={!prev}
        onClick={() => prev && onNavigate(prev)}
      >
        ‹
      </button>
      <button
        type="button"
        disabled={!today}
        onClick={() => today && onNavigate(today())}
      >
        Today
      </button>
      <button
        type="button"
        aria-label="Next period"
        disabled={!next}
        onClick={() => next && onNavigate(next)}
      >
        ›
      </button>
      <span>{title}</span>
      {views.map((view) => (
        <button
          key={view}
          type="button"
          aria-pressed={view === range.view}
          onClick={() => onNavigate(navigation.withView(view))}
        >
          {view}
        </button>
      ))}
    </Tag>
  )
}
