// packages/svelte/src/components/month/MonthWeekdays.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarDay } from '../../engine.js'
  import { useCalendarContext } from '../context'
  import { WEEKDAY, labelOf, rowsWithDays, styleText } from '../helpers'
  type MonthWeekdayScope<T> = { day: CalendarDay<T>; weekdayLabel: string }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[MonthWeekdayScope<TData>]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext<TData>()
  let first = $derived(rowsWithDays(context.calendar)[0])
</script>

{#each first.days as day (day.date)}{@const weekdayLabel = labelOf(
    day.date,
    context.locale,
    WEEKDAY
  )}<svelte:element this={as} {...rest} style={styleText({}, style)}
    >{#if children}{@render children({
        day,
        weekdayLabel
      })}{:else}{weekdayLabel}{/if}</svelte:element
  >{/each}

// packages/react/src/components/month/month-weekdays.tsx
import type { CalendarDay } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useCalendarContext } from '../context'
import {
  WEEKDAY,
  labelOf,
  renderChildren,
  rowsWithDays,
  tagOf
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type MonthWeekdayScope<TData> = {
  day: CalendarDay<TData>
  weekdayLabel: string
}

export type MonthWeekdaysProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<MonthWeekdayScope<TData>>>

export const MonthWeekdays = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: MonthWeekdaysProps<TData, TTag>): ReactNode => {
  const { calendar, locale } = useCalendarContext<TData>()
  const Tag = tagOf(as, 'div')
  const first = rowsWithDays(calendar)[0]

  return (
    <>
      {first.days.map((day) => {
        const weekdayLabel = labelOf(day.date, locale, WEEKDAY)

        return (
          <Tag key={day.date} {...rest} style={style}>
            {renderChildren(children, { day, weekdayLabel }, weekdayLabel)}
          </Tag>
        )
      })}
    </>
  )
}
