// packages/svelte/src/components/month/MonthTimedEvents.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarBox, TimedEntry } from '../../engine.js'
  import { useMonthDayContext } from '../context'
  import { styleText } from '../helpers'
  type MonthTimedEventScope<T> = { event: TimedEntry<T>; box: CalendarBox<T> }
  let {
    as = 'div',
    children,
    style,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[MonthTimedEventScope<TData>]>
    style?: string | Record<string, string | number>
    [key: string]: unknown
  } = $props()
  const context = useMonthDayContext<TData>()
</script>

{#each context.boxes as box (`${box.event.id}-${box.startMinute}`)}
  <svelte:element
    this={as}
    data-event-id={box.event.id}
    {...rest}
    style={styleText({}, style)}
  >
    {#if children}
      {@render children({ event: box.event, box })}
    {:else}
      {box.event.id}
    {/if}
  </svelte:element>
{/each}

// packages/react/src/components/month/month-timed-events.tsx
import type { CalendarBox, TimedEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useMonthDayContext } from '../context'
import { renderChildren, tagOf } from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

export type MonthTimedEventScope<TData> = {
  event: TimedEntry<TData>
  box: CalendarBox<TData>
}

export type MonthTimedEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, OwnProps<MonthTimedEventScope<TData>>>

export const MonthTimedEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  ...rest
}: MonthTimedEventsProps<TData, TTag>): ReactNode => {
  const { boxes } = useMonthDayContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {boxes.map((box) => (
        <Tag
          key={`${box.event.id}-${box.startMinute}`}
          data-event-id={box.event.id}
          {...rest}
          style={style}
        >
          {renderChildren(children, { event: box.event, box }, box.event.id)}
        </Tag>
      ))}
    </>
  )
}
