// packages/svelte/src/components/month/MonthRows.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import { useCalendarContext } from '../context'
  import type { MonthRowContextValue } from '../context'
  import { rowsWithDays } from '../helpers'
  import MonthRow from './MonthRow.svelte'
  let {
    as = 'div',
    children,
    style,
    maxLanes = null,
    laneHeight = 20,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[MonthRowContextValue<TData>]>
    style?: string | Record<string, string | number>
    maxLanes?: number | null
    laneHeight?: number
    [key: string]: unknown
  } = $props()
  const context = useCalendarContext<TData>()
  let rows = $derived(rowsWithDays(context.calendar))
</script>

{#each rows as item (item.row.start)}
  <MonthRow
    row={item.row}
    days={item.days}
    {maxLanes}
    {laneHeight}
    {as}
    {children}
    {style}
    {...rest}
  />
{/each}

// packages/react/src/components/month/month-rows.tsx
import { useCalendarContext } from '../context/calendar-context'
import { MonthRowProvider } from '../context/month-row-context'
import { rowsWithDays } from '../helpers'
import type { ReactNode } from 'react'

type MonthRowsProps = {
  children: ReactNode
  className?: string
}

export const MonthRows = <TData = any,>({
  children,
  className
}: MonthRowsProps): ReactNode => {
  const { calendar } = useCalendarContext<TData>()
  const groups = rowsWithDays(calendar)

  return (
    <>
      {groups.map(({ row, days }) => (
        <MonthRowProvider key={row.start} value={{ row, days }}>
          <div
            className={className}
            style={{
              position: 'relative',
              flex: 1
            }}
          >
            {children}
          </div>
        </MonthRowProvider>
      ))}
    </>
  )
}
