// packages/svelte/src/components/month/MonthAllDayEvents.svelte
<script lang="ts" generics="TData">
  import type { Snippet } from 'svelte'
  import type { CalendarBar, CalendarEntry } from '../../engine.js'
  import { useMonthRowContext } from '../context'
  import { percentOf, styleText, visibleLanes } from '../helpers'
  type MonthAllDayEventScope<T> = {
    event: CalendarEntry<T>
    bar: CalendarBar<T>
  }
  let {
    as = 'div',
    children,
    style,
    gap = 4,
    lanesTopOffset = 28,
    ...rest
  }: {
    as?: keyof HTMLElementTagNameMap
    children?: Snippet<[MonthAllDayEventScope<TData>]>
    style?: string | Record<string, string | number>
    gap?: number
    lanesTopOffset?: number
    [key: string]: unknown
  } = $props()
  const context = useMonthRowContext<TData>()
</script>

{#each visibleLanes(context.row.bars, context.maxLanes) as bar (`${bar.event.id}-${bar.startDay}`)}
  <svelte:element
    this={as}
    data-event-id={bar.event.id}
    data-continues-before={bar.continuesBefore}
    data-continues-after={bar.continuesAfter}
    {...rest}
    style={styleText(
      {
        position: 'absolute',
        left: `calc(${percentOf(bar.left)} + ${gap / 2}px)`,
        width: `calc(${percentOf(bar.width)} - ${gap}px)`,
        top: lanesTopOffset + bar.lane * context.laneHeight,
        height: context.laneHeight,
        zIndex: 1
      },
      style
    )}
  >
    {#if children}
      {@render children({ event: bar.event, bar })}
    {:else}
      {bar.event.id}
    {/if}
  </svelte:element>
{/each}

// packages/react/src/components/month/month-all-day-events.tsx
import type { CalendarBar, CalendarEntry } from '@midstem/chronous'
import type { ElementType, ReactNode } from 'react'

import { useMonthRowContext } from '../context'
import {
  percentOf,
  renderChildren,
  styleOf,
  tagOf,
  visibleLanes
} from '../helpers'
import type { OwnProps, PolymorphicProps } from '../types'

const GAP = 4

const LANES_TOP_OFFSET = 28

const Z_INDEX = 1

export type MonthAllDayEventScope<TData> = {
  event: CalendarEntry<TData>
  bar: CalendarBar<TData>
}

export type MonthAllDayEventsOwnProps<TData> = OwnProps<
  MonthAllDayEventScope<TData>
> & {
  gap?: number
  lanesTopOffset?: number
}

export type MonthAllDayEventsProps<
  TData,
  TTag extends ElementType = 'div'
> = PolymorphicProps<TTag, MonthAllDayEventsOwnProps<TData>>

export const MonthAllDayEvents = <TData, TTag extends ElementType = 'div'>({
  as,
  children,
  style,
  gap = GAP,
  lanesTopOffset = LANES_TOP_OFFSET,
  ...rest
}: MonthAllDayEventsProps<TData, TTag>): ReactNode => {
  const { row, maxLanes, laneHeight } = useMonthRowContext<TData>()
  const Tag = tagOf(as, 'div')

  return (
    <>
      {visibleLanes(row.bars, maxLanes).map((bar) => (
        <Tag
          key={`${bar.event.id}-${bar.startDay}`}
          data-event-id={bar.event.id}
          data-continues-before={bar.continuesBefore}
          data-continues-after={bar.continuesAfter}
          {...rest}
          style={styleOf(
            {
              position: 'absolute',
              left: `calc(${percentOf(bar.left)} + ${gap / 2}px)`,
              width: `calc(${percentOf(bar.width)} - ${gap}px)`,
              top: lanesTopOffset + bar.lane * laneHeight,
              height: laneHeight,
              zIndex: Z_INDEX
            },
            style
          )}
        >
          {renderChildren(children, { event: bar.event, bar }, bar.event.id)}
        </Tag>
      ))}
    </>
  )
}
